// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "test.proto" (package "proto2.packed", syntax proto2)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Test that proto2 packed option is respected
 *
 * @generated from protobuf message proto2.packed.PackedTest
 */
export interface PackedTest {
    /**
     * In proto2, repeated numeric fields are unpacked by default
     *
     * @generated from protobuf field: repeated int32 default_unpacked = 1
     */
    defaultUnpacked: number[];
    /**
     * Explicitly packed in proto2
     *
     * @generated from protobuf field: repeated int32 explicitly_packed = 2 [packed = true]
     */
    explicitlyPacked: number[];
    /**
     * Explicitly unpacked (even though it's the default)
     *
     * @generated from protobuf field: repeated int32 explicitly_unpacked = 3 [packed = false]
     */
    explicitlyUnpacked: number[];
    /**
     * Various types with explicit packing
     *
     * @generated from protobuf field: repeated int64 packed_int64 = 4 [packed = true]
     */
    packedInt64: string[];
    /**
     * @generated from protobuf field: repeated bool packed_bool = 5 [packed = true]
     */
    packedBool: boolean[];
    /**
     * @generated from protobuf field: repeated fixed32 packed_fixed = 6 [packed = true]
     */
    packedFixed: number[];
    /**
     * Unpacked versions
     *
     * @generated from protobuf field: repeated int64 unpacked_int64 = 7 [packed = false]
     */
    unpackedInt64: string[];
    /**
     * @generated from protobuf field: repeated bool unpacked_bool = 8 [packed = false]
     */
    unpackedBool: boolean[];
    /**
     * @generated from protobuf field: repeated fixed32 unpacked_fixed = 9 [packed = false]
     */
    unpackedFixed: number[];
}
// @generated message type with reflection information, may provide speed optimized methods
class PackedTest$Type extends MessageType<PackedTest> {
    constructor() {
        super("proto2.packed.PackedTest", [
            { no: 1, name: "default_unpacked", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "explicitly_packed", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "explicitly_unpacked", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "packed_int64", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "packed_bool", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "packed_fixed", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 7 /*ScalarType.FIXED32*/ },
            { no: 7, name: "unpacked_int64", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 3 /*ScalarType.INT64*/ },
            { no: 8, name: "unpacked_bool", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "unpacked_fixed", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 7 /*ScalarType.FIXED32*/ }
        ]);
    }
    create(value?: PartialMessage<PackedTest>): PackedTest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.defaultUnpacked = [];
        message.explicitlyPacked = [];
        message.explicitlyUnpacked = [];
        message.packedInt64 = [];
        message.packedBool = [];
        message.packedFixed = [];
        message.unpackedInt64 = [];
        message.unpackedBool = [];
        message.unpackedFixed = [];
        if (value !== undefined)
            reflectionMergePartial<PackedTest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PackedTest): PackedTest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated int32 default_unpacked */ 1:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.defaultUnpacked.push(reader.int32());
                    else
                        message.defaultUnpacked.push(reader.int32());
                    break;
                case /* repeated int32 explicitly_packed = 2 [packed = true] */ 2:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.explicitlyPacked.push(reader.int32());
                    else
                        message.explicitlyPacked.push(reader.int32());
                    break;
                case /* repeated int32 explicitly_unpacked = 3 [packed = false] */ 3:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.explicitlyUnpacked.push(reader.int32());
                    else
                        message.explicitlyUnpacked.push(reader.int32());
                    break;
                case /* repeated int64 packed_int64 = 4 [packed = true] */ 4:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.packedInt64.push(reader.int64().toString());
                    else
                        message.packedInt64.push(reader.int64().toString());
                    break;
                case /* repeated bool packed_bool = 5 [packed = true] */ 5:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.packedBool.push(reader.bool());
                    else
                        message.packedBool.push(reader.bool());
                    break;
                case /* repeated fixed32 packed_fixed = 6 [packed = true] */ 6:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.packedFixed.push(reader.fixed32());
                    else
                        message.packedFixed.push(reader.fixed32());
                    break;
                case /* repeated int64 unpacked_int64 = 7 [packed = false] */ 7:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.unpackedInt64.push(reader.int64().toString());
                    else
                        message.unpackedInt64.push(reader.int64().toString());
                    break;
                case /* repeated bool unpacked_bool = 8 [packed = false] */ 8:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.unpackedBool.push(reader.bool());
                    else
                        message.unpackedBool.push(reader.bool());
                    break;
                case /* repeated fixed32 unpacked_fixed = 9 [packed = false] */ 9:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.unpackedFixed.push(reader.fixed32());
                    else
                        message.unpackedFixed.push(reader.fixed32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PackedTest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated int32 default_unpacked = 1; */
        for (let i = 0; i < message.defaultUnpacked.length; i++)
            writer.tag(1, WireType.Varint).int32(message.defaultUnpacked[i]);
        /* repeated int32 explicitly_packed = 2 [packed = true]; */
        if (message.explicitlyPacked.length) {
            writer.tag(2, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.explicitlyPacked.length; i++)
                writer.int32(message.explicitlyPacked[i]);
            writer.join();
        }
        /* repeated int32 explicitly_unpacked = 3 [packed = false]; */
        for (let i = 0; i < message.explicitlyUnpacked.length; i++)
            writer.tag(3, WireType.Varint).int32(message.explicitlyUnpacked[i]);
        /* repeated int64 packed_int64 = 4 [packed = true]; */
        if (message.packedInt64.length) {
            writer.tag(4, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.packedInt64.length; i++)
                writer.int64(message.packedInt64[i]);
            writer.join();
        }
        /* repeated bool packed_bool = 5 [packed = true]; */
        if (message.packedBool.length) {
            writer.tag(5, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.packedBool.length; i++)
                writer.bool(message.packedBool[i]);
            writer.join();
        }
        /* repeated fixed32 packed_fixed = 6 [packed = true]; */
        if (message.packedFixed.length) {
            writer.tag(6, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.packedFixed.length; i++)
                writer.fixed32(message.packedFixed[i]);
            writer.join();
        }
        /* repeated int64 unpacked_int64 = 7 [packed = false]; */
        for (let i = 0; i < message.unpackedInt64.length; i++)
            writer.tag(7, WireType.Varint).int64(message.unpackedInt64[i]);
        /* repeated bool unpacked_bool = 8 [packed = false]; */
        for (let i = 0; i < message.unpackedBool.length; i++)
            writer.tag(8, WireType.Varint).bool(message.unpackedBool[i]);
        /* repeated fixed32 unpacked_fixed = 9 [packed = false]; */
        for (let i = 0; i < message.unpackedFixed.length; i++)
            writer.tag(9, WireType.Bit32).fixed32(message.unpackedFixed[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message proto2.packed.PackedTest
 */
export const PackedTest = new PackedTest$Type();
