// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenStatus int32

const (
	OpenStatus_OPEN_STATUS_UNKNOWN OpenStatus = 0
	OpenStatus_OPEN_STATUS_OK      OpenStatus = 1
	OpenStatus_OPEN_STATUS_ERROR   OpenStatus = 2
)

// Enum value maps for OpenStatus.
var (
	OpenStatus_name = map[int32]string{
		0: "OPEN_STATUS_UNKNOWN",
		1: "OPEN_STATUS_OK",
		2: "OPEN_STATUS_ERROR",
	}
	OpenStatus_value = map[string]int32{
		"OPEN_STATUS_UNKNOWN": 0,
		"OPEN_STATUS_OK":      1,
		"OPEN_STATUS_ERROR":   2,
	}
)

func (x OpenStatus) Enum() *OpenStatus {
	p := new(OpenStatus)
	*p = x
	return p
}

func (x OpenStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[0].Descriptor()
}

func (OpenStatus) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[0]
}

func (x OpenStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenStatus.Descriptor instead.
func (OpenStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

type CompileStatus int32

const (
	CompileStatus_STATUS_UNKNOWN CompileStatus = 0
	CompileStatus_STATUS_READY   CompileStatus = 1
	CompileStatus_STATUS_ERROR   CompileStatus = 2
	CompileStatus_STATUS_RUNNING CompileStatus = 3
)

// Enum value maps for CompileStatus.
var (
	CompileStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_READY",
		2: "STATUS_ERROR",
		3: "STATUS_RUNNING",
	}
	CompileStatus_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"STATUS_READY":   1,
		"STATUS_ERROR":   2,
		"STATUS_RUNNING": 3,
	}
)

func (x CompileStatus) Enum() *CompileStatus {
	p := new(CompileStatus)
	*p = x
	return p
}

func (x CompileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[1].Descriptor()
}

func (CompileStatus) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[1]
}

func (x CompileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompileStatus.Descriptor instead.
func (CompileStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

type LogLevel int32

const (
	LogLevel_LEVEL_DEBUG LogLevel = 0
	LogLevel_LEVEL_INFO  LogLevel = 1
	LogLevel_LEVEL_WARN  LogLevel = 2
	LogLevel_LEVEL_ERROR LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LEVEL_DEBUG",
		1: "LEVEL_INFO",
		2: "LEVEL_WARN",
		3: "LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LEVEL_DEBUG": 0,
		"LEVEL_INFO":  1,
		"LEVEL_WARN":  2,
		"LEVEL_ERROR": 3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[2].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[2]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

type CompileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LogOffset     int32                  `protobuf:"varint,2,opt,name=log_offset,json=logOffset,proto3" json:"log_offset,omitempty"`
	ProtoDir      string                 `protobuf:"bytes,3,opt,name=proto_dir,json=protoDir,proto3" json:"proto_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *CompileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompileRequest) GetLogOffset() int32 {
	if x != nil {
		return x.LogOffset
	}
	return 0
}

func (x *CompileRequest) GetProtoDir() string {
	if x != nil {
		return x.ProtoDir
	}
	return ""
}

// OpenApp opens an app from its configuration. "grpc"/
// "twirp" apps describe a gRPC/Twirp service (proto files come from a static
// directory or gRPC reflection), while built-in apps like "openapi" or "markdown"
// generate their own proto surface. In all cases the app produces proto files to
// feed into Compile, an invocation target, and the transport protocol the client
// uses to reach it. The server flattens the app's typed parameters to a string map
// for the in-process app contract.
type OpenAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *ConfigurationApp      `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAppRequest) Reset() {
	*x = OpenAppRequest{}
	mi := &file_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAppRequest) ProtoMessage() {}

func (x *OpenAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAppRequest.ProtoReflect.Descriptor instead.
func (*OpenAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *OpenAppRequest) GetApp() *ConfigurationApp {
	if x != nil {
		return x.App
	}
	return nil
}

type OpenAppResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status OpenStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=OpenStatus" json:"status,omitempty"`
	Logs   []*Log                 `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	// Directory containing the proto files to compile (only set on success). Either a
	// temp directory (generated/reflected protos) or a workspace-relative path (static
	// protos), which Compile resolves against the workspace.
	ProtoDir string `protobuf:"bytes,3,opt,name=proto_dir,json=protoDir,proto3" json:"proto_dir,omitempty"`
	// Invocation target: the upstream URL for grpc/twirp apps, or "kaja-app://<id>"
	// for in-process apps (only set on success).
	Target string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	// Transport the client uses to reach the target: "grpc" or "twirp".
	Protocol      string `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAppResponse) Reset() {
	*x = OpenAppResponse{}
	mi := &file_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAppResponse) ProtoMessage() {}

func (x *OpenAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAppResponse.ProtoReflect.Descriptor instead.
func (*OpenAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *OpenAppResponse) GetStatus() OpenStatus {
	if x != nil {
		return x.Status
	}
	return OpenStatus_OPEN_STATUS_UNKNOWN
}

func (x *OpenAppResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *OpenAppResponse) GetProtoDir() string {
	if x != nil {
		return x.ProtoDir
	}
	return ""
}

func (x *OpenAppResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *OpenAppResponse) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type CompileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CompileStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=CompileStatus" json:"status,omitempty"`
	Logs          []*Log                 `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	Sources       []*Source              `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Stub          string                 `protobuf:"bytes,4,opt,name=stub,proto3" json:"stub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *CompileResponse) GetStatus() CompileStatus {
	if x != nil {
		return x.Status
	}
	return CompileStatus_STATUS_UNKNOWN
}

func (x *CompileResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *CompileResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *CompileResponse) GetStub() string {
	if x != nil {
		return x.Stub
	}
	return ""
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *Log) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LEVEL_DEBUG
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *Source) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Source) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	mi := &file_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

type GetConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *Configuration         `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Logs          []*Log                 `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationResponse) Reset() {
	*x = GetConfigurationResponse{}
	mi := &file_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationResponse) ProtoMessage() {}

func (x *GetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigurationResponse) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *GetConfigurationResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

type Configuration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kaja can be deployed at a subpath - i.e. kaja.tools/demo
	// This field is used to set the subpath.
	// The server uses it to generate the correct paths in HTML and redirects.
	// The JS code is using relative paths and should be not dependent on this.
	PathPrefix string `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	// System-level settings (read-only, ignored in UpdateConfiguration)
	System *ConfigurationSystem `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	// Apps are the single unit of configuration. A gRPC or Twirp service is just an
	// app of type "grpc"/"twirp"; built-in integrations like "openapi" or "markdown"
	// are apps too. kaja renders and invokes every app the same way.
	Apps []*ConfigurationApp `protobuf:"bytes,5,rep,name=apps,proto3" json:"apps,omitempty"`
	// User-defined variables usable from scripts as `kaja.variables.<name>`.
	// Non-sensitive values only (base URLs, ids); stored in plaintext in kaja.json.
	Variables     map[string]string `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *Configuration) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Configuration) GetSystem() *ConfigurationSystem {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *Configuration) GetApps() []*ConfigurationApp {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *Configuration) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

type ConfigurationSystem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the UI can update configuration (true in desktop app, false in web server)
	CanUpdateConfiguration bool `protobuf:"varint,1,opt,name=can_update_configuration,json=canUpdateConfiguration,proto3" json:"can_update_configuration,omitempty"`
	// Git commit hash or tag for the currently running version
	GitRef string `protobuf:"bytes,2,opt,name=git_ref,json=gitRef,proto3" json:"git_ref,omitempty"`
	// TestFlight/App Store build number (CFBundleVersion), empty for other builds
	BuildNumber   string `protobuf:"bytes,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationSystem) Reset() {
	*x = ConfigurationSystem{}
	mi := &file_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationSystem) ProtoMessage() {}

func (x *ConfigurationSystem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationSystem.ProtoReflect.Descriptor instead.
func (*ConfigurationSystem) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigurationSystem) GetCanUpdateConfiguration() bool {
	if x != nil {
		return x.CanUpdateConfiguration
	}
	return false
}

func (x *ConfigurationSystem) GetGitRef() string {
	if x != nil {
		return x.GitRef
	}
	return ""
}

func (x *ConfigurationSystem) GetBuildNumber() string {
	if x != nil {
		return x.BuildNumber
	}
	return ""
}

// ConfigurationApp is one app: a name and exactly one typed block whose key is the
// app's type. The block declares the parameters that type needs (so two types can
// never be mixed in one app); the server flattens its scalar fields to a string map
// for the app contract.
type ConfigurationApp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to App:
	//
	//	*ConfigurationApp_Grpc
	//	*ConfigurationApp_Twirp
	//	*ConfigurationApp_Openapi
	//	*ConfigurationApp_Openai
	//	*ConfigurationApp_Markdown
	App           isConfigurationApp_App `protobuf_oneof:"app"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationApp) Reset() {
	*x = ConfigurationApp{}
	mi := &file_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationApp) ProtoMessage() {}

func (x *ConfigurationApp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationApp.ProtoReflect.Descriptor instead.
func (*ConfigurationApp) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigurationApp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigurationApp) GetApp() isConfigurationApp_App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *ConfigurationApp) GetGrpc() *GrpcApp {
	if x != nil {
		if x, ok := x.App.(*ConfigurationApp_Grpc); ok {
			return x.Grpc
		}
	}
	return nil
}

func (x *ConfigurationApp) GetTwirp() *TwirpApp {
	if x != nil {
		if x, ok := x.App.(*ConfigurationApp_Twirp); ok {
			return x.Twirp
		}
	}
	return nil
}

func (x *ConfigurationApp) GetOpenapi() *OpenApiApp {
	if x != nil {
		if x, ok := x.App.(*ConfigurationApp_Openapi); ok {
			return x.Openapi
		}
	}
	return nil
}

func (x *ConfigurationApp) GetOpenai() *OpenAiApp {
	if x != nil {
		if x, ok := x.App.(*ConfigurationApp_Openai); ok {
			return x.Openai
		}
	}
	return nil
}

func (x *ConfigurationApp) GetMarkdown() *MarkdownApp {
	if x != nil {
		if x, ok := x.App.(*ConfigurationApp_Markdown); ok {
			return x.Markdown
		}
	}
	return nil
}

type isConfigurationApp_App interface {
	isConfigurationApp_App()
}

type ConfigurationApp_Grpc struct {
	Grpc *GrpcApp `protobuf:"bytes,2,opt,name=grpc,proto3,oneof"`
}

type ConfigurationApp_Twirp struct {
	Twirp *TwirpApp `protobuf:"bytes,3,opt,name=twirp,proto3,oneof"`
}

type ConfigurationApp_Openapi struct {
	Openapi *OpenApiApp `protobuf:"bytes,4,opt,name=openapi,proto3,oneof"`
}

type ConfigurationApp_Openai struct {
	Openai *OpenAiApp `protobuf:"bytes,5,opt,name=openai,proto3,oneof"`
}

type ConfigurationApp_Markdown struct {
	Markdown *MarkdownApp `protobuf:"bytes,6,opt,name=markdown,proto3,oneof"`
}

func (*ConfigurationApp_Grpc) isConfigurationApp_App() {}

func (*ConfigurationApp_Twirp) isConfigurationApp_App() {}

func (*ConfigurationApp_Openapi) isConfigurationApp_App() {}

func (*ConfigurationApp_Openai) isConfigurationApp_App() {}

func (*ConfigurationApp_Markdown) isConfigurationApp_App() {}

// GrpcApp calls a gRPC service. Its proto surface comes from a workspace-relative
// proto_dir, or from server reflection when reflection is set. headers are
// forwarded (as metadata) with each request.
type GrpcApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ProtoDir      string                 `protobuf:"bytes,2,opt,name=proto_dir,json=protoDir,proto3" json:"proto_dir,omitempty"`
	Reflection    bool                   `protobuf:"varint,3,opt,name=reflection,proto3" json:"reflection,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcApp) Reset() {
	*x = GrpcApp{}
	mi := &file_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcApp) ProtoMessage() {}

func (x *GrpcApp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcApp.ProtoReflect.Descriptor instead.
func (*GrpcApp) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *GrpcApp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GrpcApp) GetProtoDir() string {
	if x != nil {
		return x.ProtoDir
	}
	return ""
}

func (x *GrpcApp) GetReflection() bool {
	if x != nil {
		return x.Reflection
	}
	return false
}

func (x *GrpcApp) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// TwirpApp calls a Twirp service described by a workspace-relative proto_dir.
type TwirpApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ProtoDir      string                 `protobuf:"bytes,2,opt,name=proto_dir,json=protoDir,proto3" json:"proto_dir,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwirpApp) Reset() {
	*x = TwirpApp{}
	mi := &file_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwirpApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwirpApp) ProtoMessage() {}

func (x *TwirpApp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwirpApp.ProtoReflect.Descriptor instead.
func (*TwirpApp) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *TwirpApp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TwirpApp) GetProtoDir() string {
	if x != nil {
		return x.ProtoDir
	}
	return ""
}

func (x *TwirpApp) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// OpenApiApp calls a REST API from its OpenAPI 3.x document. The document is
// taken from spec_url or, when the spec is uploaded, from spec_content (raw JSON
// or YAML). Credentials are applied per the spec's security schemes. base_url
// overrides the upstream base URL derived from the spec's servers list.
type OpenApiApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecUrl       string                 `protobuf:"bytes,1,opt,name=spec_url,json=specUrl,proto3" json:"spec_url,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SpecContent   string                 `protobuf:"bytes,6,opt,name=spec_content,json=specContent,proto3" json:"spec_content,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,7,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenApiApp) Reset() {
	*x = OpenApiApp{}
	mi := &file_proto_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenApiApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenApiApp) ProtoMessage() {}

func (x *OpenApiApp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenApiApp.ProtoReflect.Descriptor instead.
func (*OpenApiApp) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{13}
}

func (x *OpenApiApp) GetSpecUrl() string {
	if x != nil {
		return x.SpecUrl
	}
	return ""
}

func (x *OpenApiApp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *OpenApiApp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OpenApiApp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *OpenApiApp) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *OpenApiApp) GetSpecContent() string {
	if x != nil {
		return x.SpecContent
	}
	return ""
}

func (x *OpenApiApp) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

// OpenAiApp calls the OpenAI chat completions API.
type OpenAiApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAiApp) Reset() {
	*x = OpenAiApp{}
	mi := &file_proto_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAiApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAiApp) ProtoMessage() {}

func (x *OpenAiApp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAiApp.ProtoReflect.Descriptor instead.
func (*OpenAiApp) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{14}
}

func (x *OpenAiApp) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OpenAiApp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *OpenAiApp) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// MarkdownApp creates and writes Markdown files in a folder on disk. It is local,
// so it forwards no headers.
type MarkdownApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        string                 `protobuf:"bytes,1,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkdownApp) Reset() {
	*x = MarkdownApp{}
	mi := &file_proto_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkdownApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkdownApp) ProtoMessage() {}

func (x *MarkdownApp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkdownApp.ProtoReflect.Descriptor instead.
func (*MarkdownApp) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{15}
}

func (x *MarkdownApp) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type UpdateConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *Configuration         `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigurationRequest) Reset() {
	*x = UpdateConfigurationRequest{}
	mi := &file_proto_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigurationRequest) ProtoMessage() {}

func (x *UpdateConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigurationRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateConfigurationRequest) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type UpdateConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *Configuration         `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigurationResponse) Reset() {
	*x = UpdateConfigurationResponse{}
	mi := &file_proto_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigurationResponse) ProtoMessage() {}

func (x *UpdateConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigurationResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateConfigurationResponse) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

var File_proto_api_proto protoreflect.FileDescriptor

const file_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/api.proto\"\\\n" +
	"\x0eCompileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"log_offset\x18\x02 \x01(\x05R\tlogOffset\x12\x1b\n" +
	"\tproto_dir\x18\x03 \x01(\tR\bprotoDir\"5\n" +
	"\x0eOpenAppRequest\x12#\n" +
	"\x03app\x18\x01 \x01(\v2\x11.ConfigurationAppR\x03app\"\xa1\x01\n" +
	"\x0fOpenAppResponse\x12#\n" +
	"\x06status\x18\x01 \x01(\x0e2\v.OpenStatusR\x06status\x12\x18\n" +
	"\x04logs\x18\x02 \x03(\v2\x04.LogR\x04logs\x12\x1b\n" +
	"\tproto_dir\x18\x03 \x01(\tR\bprotoDir\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\"\x8a\x01\n" +
	"\x0fCompileResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.CompileStatusR\x06status\x12\x18\n" +
	"\x04logs\x18\x02 \x03(\v2\x04.LogR\x04logs\x12!\n" +
	"\asources\x18\x03 \x03(\v2\a.SourceR\asources\x12\x12\n" +
	"\x04stub\x18\x04 \x01(\tR\x04stub\"@\n" +
	"\x03Log\x12\x1f\n" +
	"\x05level\x18\x01 \x01(\x0e2\t.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"6\n" +
	"\x06Source\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x19\n" +
	"\x17GetConfigurationRequest\"j\n" +
	"\x18GetConfigurationResponse\x124\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x0e.ConfigurationR\rconfiguration\x12\x18\n" +
	"\x04logs\x18\x02 \x03(\v2\x04.LogR\x04logs\"\x90\x02\n" +
	"\rConfiguration\x12\x1f\n" +
	"\vpath_prefix\x18\x01 \x01(\tR\n" +
	"pathPrefix\x12,\n" +
	"\x06system\x18\x04 \x01(\v2\x14.ConfigurationSystemR\x06system\x12%\n" +
	"\x04apps\x18\x05 \x03(\v2\x11.ConfigurationAppR\x04apps\x12;\n" +
	"\tvariables\x18\x06 \x03(\v2\x1d.Configuration.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03R\bprojects\"\x8b\x01\n" +
	"\x13ConfigurationSystem\x128\n" +
	"\x18can_update_configuration\x18\x01 \x01(\bR\x16canUpdateConfiguration\x12\x17\n" +
	"\agit_ref\x18\x02 \x01(\tR\x06gitRef\x12!\n" +
	"\fbuild_number\x18\x03 \x01(\tR\vbuildNumber\"\xeb\x01\n" +
	"\x10ConfigurationApp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\x04grpc\x18\x02 \x01(\v2\b.GrpcAppH\x00R\x04grpc\x12!\n" +
	"\x05twirp\x18\x03 \x01(\v2\t.TwirpAppH\x00R\x05twirp\x12'\n" +
	"\aopenapi\x18\x04 \x01(\v2\v.OpenApiAppH\x00R\aopenapi\x12$\n" +
	"\x06openai\x18\x05 \x01(\v2\n" +
	".OpenAiAppH\x00R\x06openai\x12*\n" +
	"\bmarkdown\x18\x06 \x01(\v2\f.MarkdownAppH\x00R\bmarkdownB\x05\n" +
	"\x03app\"\xc5\x01\n" +
	"\aGrpcApp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tproto_dir\x18\x02 \x01(\tR\bprotoDir\x12\x1e\n" +
	"\n" +
	"reflection\x18\x03 \x01(\bR\n" +
	"reflection\x12/\n" +
	"\aheaders\x18\x04 \x03(\v2\x15.GrpcApp.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\bTwirpApp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tproto_dir\x18\x02 \x01(\tR\bprotoDir\x120\n" +
	"\aheaders\x18\x03 \x03(\v2\x16.TwirpApp.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x02\n" +
	"\n" +
	"OpenApiApp\x12\x19\n" +
	"\bspec_url\x18\x01 \x01(\tR\aspecUrl\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x122\n" +
	"\aheaders\x18\x05 \x03(\v2\x18.OpenApiApp.HeadersEntryR\aheaders\x12!\n" +
	"\fspec_content\x18\x06 \x01(\tR\vspecContent\x12\x19\n" +
	"\bbase_url\x18\a \x01(\tR\abaseUrl\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x01\n" +
	"\tOpenAiApp\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x121\n" +
	"\aheaders\x18\x03 \x03(\v2\x17.OpenAiApp.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\vMarkdownApp\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\"R\n" +
	"\x1aUpdateConfigurationRequest\x124\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x0e.ConfigurationR\rconfiguration\"S\n" +
	"\x1bUpdateConfigurationResponse\x124\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x0e.ConfigurationR\rconfiguration*P\n" +
	"\n" +
	"OpenStatus\x12\x17\n" +
	"\x13OPEN_STATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eOPEN_STATUS_OK\x10\x01\x12\x15\n" +
	"\x11OPEN_STATUS_ERROR\x10\x02*[\n" +
	"\rCompileStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x10\n" +
	"\fSTATUS_READY\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x02\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x03*L\n" +
	"\bLogLevel\x12\x0f\n" +
	"\vLEVEL_DEBUG\x10\x00\x12\x0e\n" +
	"\n" +
	"LEVEL_INFO\x10\x01\x12\x0e\n" +
	"\n" +
	"LEVEL_WARN\x10\x02\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x032\xfc\x01\n" +
	"\x03Api\x12,\n" +
	"\aCompile\x12\x0f.CompileRequest\x1a\x10.CompileResponse\x12,\n" +
	"\aOpenApp\x12\x0f.OpenAppRequest\x1a\x10.OpenAppResponse\x12G\n" +
	"\x10GetConfiguration\x12\x18.GetConfigurationRequest\x1a\x19.GetConfigurationResponse\x12P\n" +
	"\x13UpdateConfiguration\x12\x1b.UpdateConfigurationRequest\x1a\x1c.UpdateConfigurationResponseB\tZ\apkg/apib\x06proto3"

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData []byte
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)))
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_api_proto_goTypes = []any{
	(OpenStatus)(0),                     // 0: OpenStatus
	(CompileStatus)(0),                  // 1: CompileStatus
	(LogLevel)(0),                       // 2: LogLevel
	(*CompileRequest)(nil),              // 3: CompileRequest
	(*OpenAppRequest)(nil),              // 4: OpenAppRequest
	(*OpenAppResponse)(nil),             // 5: OpenAppResponse
	(*CompileResponse)(nil),             // 6: CompileResponse
	(*Log)(nil),                         // 7: Log
	(*Source)(nil),                      // 8: Source
	(*GetConfigurationRequest)(nil),     // 9: GetConfigurationRequest
	(*GetConfigurationResponse)(nil),    // 10: GetConfigurationResponse
	(*Configuration)(nil),               // 11: Configuration
	(*ConfigurationSystem)(nil),         // 12: ConfigurationSystem
	(*ConfigurationApp)(nil),            // 13: ConfigurationApp
	(*GrpcApp)(nil),                     // 14: GrpcApp
	(*TwirpApp)(nil),                    // 15: TwirpApp
	(*OpenApiApp)(nil),                  // 16: OpenApiApp
	(*OpenAiApp)(nil),                   // 17: OpenAiApp
	(*MarkdownApp)(nil),                 // 18: MarkdownApp
	(*UpdateConfigurationRequest)(nil),  // 19: UpdateConfigurationRequest
	(*UpdateConfigurationResponse)(nil), // 20: UpdateConfigurationResponse
	nil,                                 // 21: Configuration.VariablesEntry
	nil,                                 // 22: GrpcApp.HeadersEntry
	nil,                                 // 23: TwirpApp.HeadersEntry
	nil,                                 // 24: OpenApiApp.HeadersEntry
	nil,                                 // 25: OpenAiApp.HeadersEntry
}
var file_proto_api_proto_depIdxs = []int32{
	13, // 0: OpenAppRequest.app:type_name -> ConfigurationApp
	0,  // 1: OpenAppResponse.status:type_name -> OpenStatus
	7,  // 2: OpenAppResponse.logs:type_name -> Log
	1,  // 3: CompileResponse.status:type_name -> CompileStatus
	7,  // 4: CompileResponse.logs:type_name -> Log
	8,  // 5: CompileResponse.sources:type_name -> Source
	2,  // 6: Log.level:type_name -> LogLevel
	11, // 7: GetConfigurationResponse.configuration:type_name -> Configuration
	7,  // 8: GetConfigurationResponse.logs:type_name -> Log
	12, // 9: Configuration.system:type_name -> ConfigurationSystem
	13, // 10: Configuration.apps:type_name -> ConfigurationApp
	21, // 11: Configuration.variables:type_name -> Configuration.VariablesEntry
	14, // 12: ConfigurationApp.grpc:type_name -> GrpcApp
	15, // 13: ConfigurationApp.twirp:type_name -> TwirpApp
	16, // 14: ConfigurationApp.openapi:type_name -> OpenApiApp
	17, // 15: ConfigurationApp.openai:type_name -> OpenAiApp
	18, // 16: ConfigurationApp.markdown:type_name -> MarkdownApp
	22, // 17: GrpcApp.headers:type_name -> GrpcApp.HeadersEntry
	23, // 18: TwirpApp.headers:type_name -> TwirpApp.HeadersEntry
	24, // 19: OpenApiApp.headers:type_name -> OpenApiApp.HeadersEntry
	25, // 20: OpenAiApp.headers:type_name -> OpenAiApp.HeadersEntry
	11, // 21: UpdateConfigurationRequest.configuration:type_name -> Configuration
	11, // 22: UpdateConfigurationResponse.configuration:type_name -> Configuration
	3,  // 23: Api.Compile:input_type -> CompileRequest
	4,  // 24: Api.OpenApp:input_type -> OpenAppRequest
	9,  // 25: Api.GetConfiguration:input_type -> GetConfigurationRequest
	19, // 26: Api.UpdateConfiguration:input_type -> UpdateConfigurationRequest
	6,  // 27: Api.Compile:output_type -> CompileResponse
	5,  // 28: Api.OpenApp:output_type -> OpenAppResponse
	10, // 29: Api.GetConfiguration:output_type -> GetConfigurationResponse
	20, // 30: Api.UpdateConfiguration:output_type -> UpdateConfigurationResponse
	27, // [27:31] is the sub-list for method output_type
	23, // [23:27] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	file_proto_api_proto_msgTypes[10].OneofWrappers = []any{
		(*ConfigurationApp_Grpc)(nil),
		(*ConfigurationApp_Twirp)(nil),
		(*ConfigurationApp_Openapi)(nil),
		(*ConfigurationApp_Openai)(nil),
		(*ConfigurationApp_Markdown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		EnumInfos:         file_proto_api_proto_enumTypes,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}
