// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReflectStatus int32

const (
	ReflectStatus_REFLECT_STATUS_UNKNOWN ReflectStatus = 0
	ReflectStatus_REFLECT_STATUS_OK      ReflectStatus = 1
	ReflectStatus_REFLECT_STATUS_ERROR   ReflectStatus = 2
)

// Enum value maps for ReflectStatus.
var (
	ReflectStatus_name = map[int32]string{
		0: "REFLECT_STATUS_UNKNOWN",
		1: "REFLECT_STATUS_OK",
		2: "REFLECT_STATUS_ERROR",
	}
	ReflectStatus_value = map[string]int32{
		"REFLECT_STATUS_UNKNOWN": 0,
		"REFLECT_STATUS_OK":      1,
		"REFLECT_STATUS_ERROR":   2,
	}
)

func (x ReflectStatus) Enum() *ReflectStatus {
	p := new(ReflectStatus)
	*p = x
	return p
}

func (x ReflectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReflectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[0].Descriptor()
}

func (ReflectStatus) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[0]
}

func (x ReflectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReflectStatus.Descriptor instead.
func (ReflectStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

type CompileStatus int32

const (
	CompileStatus_STATUS_UNKNOWN CompileStatus = 0
	CompileStatus_STATUS_READY   CompileStatus = 1
	CompileStatus_STATUS_ERROR   CompileStatus = 2
	CompileStatus_STATUS_RUNNING CompileStatus = 3
)

// Enum value maps for CompileStatus.
var (
	CompileStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_READY",
		2: "STATUS_ERROR",
		3: "STATUS_RUNNING",
	}
	CompileStatus_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"STATUS_READY":   1,
		"STATUS_ERROR":   2,
		"STATUS_RUNNING": 3,
	}
)

func (x CompileStatus) Enum() *CompileStatus {
	p := new(CompileStatus)
	*p = x
	return p
}

func (x CompileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[1].Descriptor()
}

func (CompileStatus) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[1]
}

func (x CompileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompileStatus.Descriptor instead.
func (CompileStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

type LogLevel int32

const (
	LogLevel_LEVEL_DEBUG LogLevel = 0
	LogLevel_LEVEL_INFO  LogLevel = 1
	LogLevel_LEVEL_WARN  LogLevel = 2
	LogLevel_LEVEL_ERROR LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LEVEL_DEBUG",
		1: "LEVEL_INFO",
		2: "LEVEL_WARN",
		3: "LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LEVEL_DEBUG": 0,
		"LEVEL_INFO":  1,
		"LEVEL_WARN":  2,
		"LEVEL_ERROR": 3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[2].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[2]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

type RpcProtocol int32

const (
	RpcProtocol_RPC_PROTOCOL_UNSPECIFIED RpcProtocol = 0
	RpcProtocol_RPC_PROTOCOL_GRPC        RpcProtocol = 1
	RpcProtocol_RPC_PROTOCOL_TWIRP       RpcProtocol = 2
)

// Enum value maps for RpcProtocol.
var (
	RpcProtocol_name = map[int32]string{
		0: "RPC_PROTOCOL_UNSPECIFIED",
		1: "RPC_PROTOCOL_GRPC",
		2: "RPC_PROTOCOL_TWIRP",
	}
	RpcProtocol_value = map[string]int32{
		"RPC_PROTOCOL_UNSPECIFIED": 0,
		"RPC_PROTOCOL_GRPC":        1,
		"RPC_PROTOCOL_TWIRP":       2,
	}
)

func (x RpcProtocol) Enum() *RpcProtocol {
	p := new(RpcProtocol)
	*p = x
	return p
}

func (x RpcProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[3].Descriptor()
}

func (RpcProtocol) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[3]
}

func (x RpcProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcProtocol.Descriptor instead.
func (RpcProtocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

type CompileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LogOffset     int32                  `protobuf:"varint,2,opt,name=log_offset,json=logOffset,proto3" json:"log_offset,omitempty"`
	ProtoDir      string                 `protobuf:"bytes,3,opt,name=proto_dir,json=protoDir,proto3" json:"proto_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *CompileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompileRequest) GetLogOffset() int32 {
	if x != nil {
		return x.LogOffset
	}
	return 0
}

func (x *CompileRequest) GetProtoDir() string {
	if x != nil {
		return x.ProtoDir
	}
	return ""
}

type ReflectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // Target gRPC server URL for reflection discovery
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReflectRequest) Reset() {
	*x = ReflectRequest{}
	mi := &file_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReflectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReflectRequest) ProtoMessage() {}

func (x *ReflectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReflectRequest.ProtoReflect.Descriptor instead.
func (*ReflectRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *ReflectRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ReflectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReflectStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=ReflectStatus" json:"status,omitempty"`
	Logs          []*Log                 `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	ProtoDir      string                 `protobuf:"bytes,3,opt,name=proto_dir,json=protoDir,proto3" json:"proto_dir,omitempty"` // Temp directory containing discovered proto files (only set on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReflectResponse) Reset() {
	*x = ReflectResponse{}
	mi := &file_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReflectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReflectResponse) ProtoMessage() {}

func (x *ReflectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReflectResponse.ProtoReflect.Descriptor instead.
func (*ReflectResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *ReflectResponse) GetStatus() ReflectStatus {
	if x != nil {
		return x.Status
	}
	return ReflectStatus_REFLECT_STATUS_UNKNOWN
}

func (x *ReflectResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ReflectResponse) GetProtoDir() string {
	if x != nil {
		return x.ProtoDir
	}
	return ""
}

// OpenApp instantiates a built-in app (e.g. the OpenAPI app) from its creation
// parameters. The app generates proto files describing its services/methods and
// returns the temp directory they live in, ready to feed into Compile - the same
// way Reflect works for gRPC reflection. The returned target is used as the
// project URL so method calls are routed back to the app for invocation.
type OpenAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                                                       // Built-in app type, e.g. "openapi"
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // App-specific creation parameters, e.g. {"spec_url": "..."}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAppRequest) Reset() {
	*x = OpenAppRequest{}
	mi := &file_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAppRequest) ProtoMessage() {}

func (x *OpenAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAppRequest.ProtoReflect.Descriptor instead.
func (*OpenAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *OpenAppRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OpenAppRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type OpenAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReflectStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=ReflectStatus" json:"status,omitempty"`
	Logs          []*Log                 `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	ProtoDir      string                 `protobuf:"bytes,3,opt,name=proto_dir,json=protoDir,proto3" json:"proto_dir,omitempty"` // Temp directory containing generated proto files (only set on success)
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`                     // Invocation target for the app instance, e.g. "kaja-app://<id>" (only set on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAppResponse) Reset() {
	*x = OpenAppResponse{}
	mi := &file_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAppResponse) ProtoMessage() {}

func (x *OpenAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAppResponse.ProtoReflect.Descriptor instead.
func (*OpenAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *OpenAppResponse) GetStatus() ReflectStatus {
	if x != nil {
		return x.Status
	}
	return ReflectStatus_REFLECT_STATUS_UNKNOWN
}

func (x *OpenAppResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *OpenAppResponse) GetProtoDir() string {
	if x != nil {
		return x.ProtoDir
	}
	return ""
}

func (x *OpenAppResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type CompileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CompileStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=CompileStatus" json:"status,omitempty"`
	Logs          []*Log                 `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	Sources       []*Source              `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Stub          string                 `protobuf:"bytes,4,opt,name=stub,proto3" json:"stub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *CompileResponse) GetStatus() CompileStatus {
	if x != nil {
		return x.Status
	}
	return CompileStatus_STATUS_UNKNOWN
}

func (x *CompileResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *CompileResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *CompileResponse) GetStub() string {
	if x != nil {
		return x.Stub
	}
	return ""
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *Log) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LEVEL_DEBUG
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *Source) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Source) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	mi := &file_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

type GetConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *Configuration         `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Logs          []*Log                 `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationResponse) Reset() {
	*x = GetConfigurationResponse{}
	mi := &file_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationResponse) ProtoMessage() {}

func (x *GetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetConfigurationResponse) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *GetConfigurationResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

type Configuration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kaja can be deployed at a subpath - i.e. kaja.tools/demo
	// This field is used to set the subpath.
	// The server uses it to generate the correct paths in HTML and redirects.
	// The JS code is using relative paths and should be not dependent on this.
	PathPrefix string                  `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Projects   []*ConfigurationProject `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
	// System-level settings (read-only, ignored in UpdateConfiguration)
	System *ConfigurationSystem `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	// Apps are an alternative to projects: instead of pointing at a gRPC/Twirp
	// service, an app is a built-in (or, later, remote) integration that exposes
	// a proto surface kaja renders and invokes the same way as a project.
	Apps          []*ConfigurationApp `protobuf:"bytes,5,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *Configuration) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Configuration) GetProjects() []*ConfigurationProject {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *Configuration) GetSystem() *ConfigurationSystem {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *Configuration) GetApps() []*ConfigurationApp {
	if x != nil {
		return x.Apps
	}
	return nil
}

type ConfigurationSystem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the UI can update configuration (true in desktop app, false in web server)
	CanUpdateConfiguration bool `protobuf:"varint,1,opt,name=can_update_configuration,json=canUpdateConfiguration,proto3" json:"can_update_configuration,omitempty"`
	// Git commit hash or tag for the currently running version
	GitRef string `protobuf:"bytes,2,opt,name=git_ref,json=gitRef,proto3" json:"git_ref,omitempty"`
	// TestFlight/App Store build number (CFBundleVersion), empty for other builds
	BuildNumber   string `protobuf:"bytes,3,opt,name=build_number,json=buildNumber,proto3" json:"build_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationSystem) Reset() {
	*x = ConfigurationSystem{}
	mi := &file_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationSystem) ProtoMessage() {}

func (x *ConfigurationSystem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationSystem.ProtoReflect.Descriptor instead.
func (*ConfigurationSystem) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigurationSystem) GetCanUpdateConfiguration() bool {
	if x != nil {
		return x.CanUpdateConfiguration
	}
	return false
}

func (x *ConfigurationSystem) GetGitRef() string {
	if x != nil {
		return x.GitRef
	}
	return ""
}

func (x *ConfigurationSystem) GetBuildNumber() string {
	if x != nil {
		return x.BuildNumber
	}
	return ""
}

type ConfigurationProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      RpcProtocol            `protobuf:"varint,2,opt,name=protocol,proto3,enum=RpcProtocol" json:"protocol,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	ProtoDir      string                 `protobuf:"bytes,4,opt,name=proto_dir,json=protoDir,proto3" json:"proto_dir,omitempty"`
	UseReflection bool                   `protobuf:"varint,5,opt,name=use_reflection,json=useReflection,proto3" json:"use_reflection,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationProject) Reset() {
	*x = ConfigurationProject{}
	mi := &file_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationProject) ProtoMessage() {}

func (x *ConfigurationProject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationProject.ProtoReflect.Descriptor instead.
func (*ConfigurationProject) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigurationProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigurationProject) GetProtocol() RpcProtocol {
	if x != nil {
		return x.Protocol
	}
	return RpcProtocol_RPC_PROTOCOL_UNSPECIFIED
}

func (x *ConfigurationProject) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ConfigurationProject) GetProtoDir() string {
	if x != nil {
		return x.ProtoDir
	}
	return ""
}

func (x *ConfigurationProject) GetUseReflection() bool {
	if x != nil {
		return x.UseReflection
	}
	return false
}

func (x *ConfigurationProject) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ConfigurationApp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Built-in app type, e.g. "openapi" or "markdown".
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// App-specific creation parameters. For "openapi": {"spec_url": "<url>"};
	// for "markdown": {"path": "<file>"}.
	Parameters map[string]string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Headers sent with each request the app makes to the upstream service.
	Headers       map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationApp) Reset() {
	*x = ConfigurationApp{}
	mi := &file_proto_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationApp) ProtoMessage() {}

func (x *ConfigurationApp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationApp.ProtoReflect.Descriptor instead.
func (*ConfigurationApp) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigurationApp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigurationApp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigurationApp) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ConfigurationApp) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type UpdateConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *Configuration         `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigurationRequest) Reset() {
	*x = UpdateConfigurationRequest{}
	mi := &file_proto_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigurationRequest) ProtoMessage() {}

func (x *UpdateConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigurationRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateConfigurationRequest) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type UpdateConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *Configuration         `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigurationResponse) Reset() {
	*x = UpdateConfigurationResponse{}
	mi := &file_proto_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigurationResponse) ProtoMessage() {}

func (x *UpdateConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigurationResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateConfigurationResponse) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

var File_proto_api_proto protoreflect.FileDescriptor

const file_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/api.proto\"\\\n" +
	"\x0eCompileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"log_offset\x18\x02 \x01(\x05R\tlogOffset\x12\x1b\n" +
	"\tproto_dir\x18\x03 \x01(\tR\bprotoDir\"\"\n" +
	"\x0eReflectRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"p\n" +
	"\x0fReflectResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.ReflectStatusR\x06status\x12\x18\n" +
	"\x04logs\x18\x02 \x03(\v2\x04.LogR\x04logs\x12\x1b\n" +
	"\tproto_dir\x18\x03 \x01(\tR\bprotoDir\"\xa4\x01\n" +
	"\x0eOpenAppRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12?\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2\x1f.OpenAppRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\x0fOpenAppResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.ReflectStatusR\x06status\x12\x18\n" +
	"\x04logs\x18\x02 \x03(\v2\x04.LogR\x04logs\x12\x1b\n" +
	"\tproto_dir\x18\x03 \x01(\tR\bprotoDir\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\"\x8a\x01\n" +
	"\x0fCompileResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.CompileStatusR\x06status\x12\x18\n" +
	"\x04logs\x18\x02 \x03(\v2\x04.LogR\x04logs\x12!\n" +
	"\asources\x18\x03 \x03(\v2\a.SourceR\asources\x12\x12\n" +
	"\x04stub\x18\x04 \x01(\tR\x04stub\"@\n" +
	"\x03Log\x12\x1f\n" +
	"\x05level\x18\x01 \x01(\x0e2\t.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"6\n" +
	"\x06Source\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x19\n" +
	"\x17GetConfigurationRequest\"j\n" +
	"\x18GetConfigurationResponse\x124\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x0e.ConfigurationR\rconfiguration\x12\x18\n" +
	"\x04logs\x18\x02 \x03(\v2\x04.LogR\x04logs\"\xb8\x01\n" +
	"\rConfiguration\x12\x1f\n" +
	"\vpath_prefix\x18\x01 \x01(\tR\n" +
	"pathPrefix\x121\n" +
	"\bprojects\x18\x02 \x03(\v2\x15.ConfigurationProjectR\bprojects\x12,\n" +
	"\x06system\x18\x04 \x01(\v2\x14.ConfigurationSystemR\x06system\x12%\n" +
	"\x04apps\x18\x05 \x03(\v2\x11.ConfigurationAppR\x04apps\"\x8b\x01\n" +
	"\x13ConfigurationSystem\x128\n" +
	"\x18can_update_configuration\x18\x01 \x01(\bR\x16canUpdateConfiguration\x12\x17\n" +
	"\agit_ref\x18\x02 \x01(\tR\x06gitRef\x12!\n" +
	"\fbuild_number\x18\x03 \x01(\tR\vbuildNumber\"\xa4\x02\n" +
	"\x14ConfigurationProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\f.RpcProtocolR\bprotocol\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1b\n" +
	"\tproto_dir\x18\x04 \x01(\tR\bprotoDir\x12%\n" +
	"\x0euse_reflection\x18\x05 \x01(\bR\ruseReflection\x12<\n" +
	"\aheaders\x18\x06 \x03(\v2\".ConfigurationProject.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x02\n" +
	"\x10ConfigurationApp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12A\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2!.ConfigurationApp.ParametersEntryR\n" +
	"parameters\x128\n" +
	"\aheaders\x18\x04 \x03(\v2\x1e.ConfigurationApp.HeadersEntryR\aheaders\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x1aUpdateConfigurationRequest\x124\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x0e.ConfigurationR\rconfiguration\"S\n" +
	"\x1bUpdateConfigurationResponse\x124\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x0e.ConfigurationR\rconfiguration*\\\n" +
	"\rReflectStatus\x12\x1a\n" +
	"\x16REFLECT_STATUS_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11REFLECT_STATUS_OK\x10\x01\x12\x18\n" +
	"\x14REFLECT_STATUS_ERROR\x10\x02*[\n" +
	"\rCompileStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x10\n" +
	"\fSTATUS_READY\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x02\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x03*L\n" +
	"\bLogLevel\x12\x0f\n" +
	"\vLEVEL_DEBUG\x10\x00\x12\x0e\n" +
	"\n" +
	"LEVEL_INFO\x10\x01\x12\x0e\n" +
	"\n" +
	"LEVEL_WARN\x10\x02\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x03*Z\n" +
	"\vRpcProtocol\x12\x1c\n" +
	"\x18RPC_PROTOCOL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RPC_PROTOCOL_GRPC\x10\x01\x12\x16\n" +
	"\x12RPC_PROTOCOL_TWIRP\x10\x022\xaa\x02\n" +
	"\x03Api\x12,\n" +
	"\aCompile\x12\x0f.CompileRequest\x1a\x10.CompileResponse\x12,\n" +
	"\aReflect\x12\x0f.ReflectRequest\x1a\x10.ReflectResponse\x12,\n" +
	"\aOpenApp\x12\x0f.OpenAppRequest\x1a\x10.OpenAppResponse\x12G\n" +
	"\x10GetConfiguration\x12\x18.GetConfigurationRequest\x1a\x19.GetConfigurationResponse\x12P\n" +
	"\x13UpdateConfiguration\x12\x1b.UpdateConfigurationRequest\x1a\x1c.UpdateConfigurationResponseB\tZ\apkg/apib\x06proto3"

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData []byte
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)))
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_api_proto_goTypes = []any{
	(ReflectStatus)(0),                  // 0: ReflectStatus
	(CompileStatus)(0),                  // 1: CompileStatus
	(LogLevel)(0),                       // 2: LogLevel
	(RpcProtocol)(0),                    // 3: RpcProtocol
	(*CompileRequest)(nil),              // 4: CompileRequest
	(*ReflectRequest)(nil),              // 5: ReflectRequest
	(*ReflectResponse)(nil),             // 6: ReflectResponse
	(*OpenAppRequest)(nil),              // 7: OpenAppRequest
	(*OpenAppResponse)(nil),             // 8: OpenAppResponse
	(*CompileResponse)(nil),             // 9: CompileResponse
	(*Log)(nil),                         // 10: Log
	(*Source)(nil),                      // 11: Source
	(*GetConfigurationRequest)(nil),     // 12: GetConfigurationRequest
	(*GetConfigurationResponse)(nil),    // 13: GetConfigurationResponse
	(*Configuration)(nil),               // 14: Configuration
	(*ConfigurationSystem)(nil),         // 15: ConfigurationSystem
	(*ConfigurationProject)(nil),        // 16: ConfigurationProject
	(*ConfigurationApp)(nil),            // 17: ConfigurationApp
	(*UpdateConfigurationRequest)(nil),  // 18: UpdateConfigurationRequest
	(*UpdateConfigurationResponse)(nil), // 19: UpdateConfigurationResponse
	nil,                                 // 20: OpenAppRequest.ParametersEntry
	nil,                                 // 21: ConfigurationProject.HeadersEntry
	nil,                                 // 22: ConfigurationApp.ParametersEntry
	nil,                                 // 23: ConfigurationApp.HeadersEntry
}
var file_proto_api_proto_depIdxs = []int32{
	0,  // 0: ReflectResponse.status:type_name -> ReflectStatus
	10, // 1: ReflectResponse.logs:type_name -> Log
	20, // 2: OpenAppRequest.parameters:type_name -> OpenAppRequest.ParametersEntry
	0,  // 3: OpenAppResponse.status:type_name -> ReflectStatus
	10, // 4: OpenAppResponse.logs:type_name -> Log
	1,  // 5: CompileResponse.status:type_name -> CompileStatus
	10, // 6: CompileResponse.logs:type_name -> Log
	11, // 7: CompileResponse.sources:type_name -> Source
	2,  // 8: Log.level:type_name -> LogLevel
	14, // 9: GetConfigurationResponse.configuration:type_name -> Configuration
	10, // 10: GetConfigurationResponse.logs:type_name -> Log
	16, // 11: Configuration.projects:type_name -> ConfigurationProject
	15, // 12: Configuration.system:type_name -> ConfigurationSystem
	17, // 13: Configuration.apps:type_name -> ConfigurationApp
	3,  // 14: ConfigurationProject.protocol:type_name -> RpcProtocol
	21, // 15: ConfigurationProject.headers:type_name -> ConfigurationProject.HeadersEntry
	22, // 16: ConfigurationApp.parameters:type_name -> ConfigurationApp.ParametersEntry
	23, // 17: ConfigurationApp.headers:type_name -> ConfigurationApp.HeadersEntry
	14, // 18: UpdateConfigurationRequest.configuration:type_name -> Configuration
	14, // 19: UpdateConfigurationResponse.configuration:type_name -> Configuration
	4,  // 20: Api.Compile:input_type -> CompileRequest
	5,  // 21: Api.Reflect:input_type -> ReflectRequest
	7,  // 22: Api.OpenApp:input_type -> OpenAppRequest
	12, // 23: Api.GetConfiguration:input_type -> GetConfigurationRequest
	18, // 24: Api.UpdateConfiguration:input_type -> UpdateConfigurationRequest
	9,  // 25: Api.Compile:output_type -> CompileResponse
	6,  // 26: Api.Reflect:output_type -> ReflectResponse
	8,  // 27: Api.OpenApp:output_type -> OpenAppResponse
	13, // 28: Api.GetConfiguration:output_type -> GetConfigurationResponse
	19, // 29: Api.UpdateConfiguration:output_type -> UpdateConfigurationResponse
	25, // [25:30] is the sub-list for method output_type
	20, // [20:25] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		EnumInfos:         file_proto_api_proto_enumTypes,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}
