// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: proto/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReflectStatus int32

const (
	ReflectStatus_REFLECT_STATUS_UNKNOWN ReflectStatus = 0
	ReflectStatus_REFLECT_STATUS_OK      ReflectStatus = 1
	ReflectStatus_REFLECT_STATUS_ERROR   ReflectStatus = 2
)

// Enum value maps for ReflectStatus.
var (
	ReflectStatus_name = map[int32]string{
		0: "REFLECT_STATUS_UNKNOWN",
		1: "REFLECT_STATUS_OK",
		2: "REFLECT_STATUS_ERROR",
	}
	ReflectStatus_value = map[string]int32{
		"REFLECT_STATUS_UNKNOWN": 0,
		"REFLECT_STATUS_OK":      1,
		"REFLECT_STATUS_ERROR":   2,
	}
)

func (x ReflectStatus) Enum() *ReflectStatus {
	p := new(ReflectStatus)
	*p = x
	return p
}

func (x ReflectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReflectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[0].Descriptor()
}

func (ReflectStatus) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[0]
}

func (x ReflectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReflectStatus.Descriptor instead.
func (ReflectStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

type CompileStatus int32

const (
	CompileStatus_STATUS_UNKNOWN CompileStatus = 0
	CompileStatus_STATUS_READY   CompileStatus = 1
	CompileStatus_STATUS_ERROR   CompileStatus = 2
	CompileStatus_STATUS_RUNNING CompileStatus = 3
)

// Enum value maps for CompileStatus.
var (
	CompileStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_READY",
		2: "STATUS_ERROR",
		3: "STATUS_RUNNING",
	}
	CompileStatus_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"STATUS_READY":   1,
		"STATUS_ERROR":   2,
		"STATUS_RUNNING": 3,
	}
)

func (x CompileStatus) Enum() *CompileStatus {
	p := new(CompileStatus)
	*p = x
	return p
}

func (x CompileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[1].Descriptor()
}

func (CompileStatus) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[1]
}

func (x CompileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompileStatus.Descriptor instead.
func (CompileStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

type LogLevel int32

const (
	LogLevel_LEVEL_DEBUG LogLevel = 0
	LogLevel_LEVEL_INFO  LogLevel = 1
	LogLevel_LEVEL_WARN  LogLevel = 2
	LogLevel_LEVEL_ERROR LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LEVEL_DEBUG",
		1: "LEVEL_INFO",
		2: "LEVEL_WARN",
		3: "LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LEVEL_DEBUG": 0,
		"LEVEL_INFO":  1,
		"LEVEL_WARN":  2,
		"LEVEL_ERROR": 3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[2].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[2]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

type RpcProtocol int32

const (
	RpcProtocol_RPC_PROTOCOL_TWIRP RpcProtocol = 0
	RpcProtocol_RPC_PROTOCOL_GRPC  RpcProtocol = 1
)

// Enum value maps for RpcProtocol.
var (
	RpcProtocol_name = map[int32]string{
		0: "RPC_PROTOCOL_TWIRP",
		1: "RPC_PROTOCOL_GRPC",
	}
	RpcProtocol_value = map[string]int32{
		"RPC_PROTOCOL_TWIRP": 0,
		"RPC_PROTOCOL_GRPC":  1,
	}
)

func (x RpcProtocol) Enum() *RpcProtocol {
	p := new(RpcProtocol)
	*p = x
	return p
}

func (x RpcProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_proto_enumTypes[3].Descriptor()
}

func (RpcProtocol) Type() protoreflect.EnumType {
	return &file_proto_api_proto_enumTypes[3]
}

func (x RpcProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcProtocol.Descriptor instead.
func (RpcProtocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

type CompileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LogOffset     int32                  `protobuf:"varint,2,opt,name=log_offset,json=logOffset,proto3" json:"log_offset,omitempty"`
	ProtoDir      string                 `protobuf:"bytes,3,opt,name=proto_dir,json=protoDir,proto3" json:"proto_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *CompileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompileRequest) GetLogOffset() int32 {
	if x != nil {
		return x.LogOffset
	}
	return 0
}

func (x *CompileRequest) GetProtoDir() string {
	if x != nil {
		return x.ProtoDir
	}
	return ""
}

type ReflectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // Target gRPC server URL for reflection discovery
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReflectRequest) Reset() {
	*x = ReflectRequest{}
	mi := &file_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReflectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReflectRequest) ProtoMessage() {}

func (x *ReflectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReflectRequest.ProtoReflect.Descriptor instead.
func (*ReflectRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *ReflectRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ReflectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReflectStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=ReflectStatus" json:"status,omitempty"`
	Logs          []*Log                 `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	ProtoDir      string                 `protobuf:"bytes,3,opt,name=proto_dir,json=protoDir,proto3" json:"proto_dir,omitempty"` // Temp directory containing discovered proto files (only set on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReflectResponse) Reset() {
	*x = ReflectResponse{}
	mi := &file_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReflectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReflectResponse) ProtoMessage() {}

func (x *ReflectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReflectResponse.ProtoReflect.Descriptor instead.
func (*ReflectResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *ReflectResponse) GetStatus() ReflectStatus {
	if x != nil {
		return x.Status
	}
	return ReflectStatus_REFLECT_STATUS_UNKNOWN
}

func (x *ReflectResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ReflectResponse) GetProtoDir() string {
	if x != nil {
		return x.ProtoDir
	}
	return ""
}

type CompileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CompileStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=CompileStatus" json:"status,omitempty"`
	Logs          []*Log                 `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	Sources       []*Source              `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Stub          string                 `protobuf:"bytes,4,opt,name=stub,proto3" json:"stub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *CompileResponse) GetStatus() CompileStatus {
	if x != nil {
		return x.Status
	}
	return CompileStatus_STATUS_UNKNOWN
}

func (x *CompileResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *CompileResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *CompileResponse) GetStub() string {
	if x != nil {
		return x.Stub
	}
	return ""
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *Log) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LEVEL_DEBUG
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *Source) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Source) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	mi := &file_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{6}
}

type GetConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *Configuration         `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Logs          []*Log                 `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationResponse) Reset() {
	*x = GetConfigurationResponse{}
	mi := &file_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationResponse) ProtoMessage() {}

func (x *GetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigurationResponse) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *GetConfigurationResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

type Configuration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kaja can be deployed at a subpath - i.e. kaja.tools/demo
	// This field is used to set the subpath.
	// The server uses it to generate the correct paths in HTML and redirects.
	// The JS code is using relative paths and should be not dependent on this.
	PathPrefix string                  `protobuf:"bytes,1,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Projects   []*ConfigurationProject `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
	Ai         *ConfigurationAI        `protobuf:"bytes,3,opt,name=ai,proto3" json:"ai,omitempty"`
	// System-level settings (read-only, ignored in UpdateConfiguration)
	System        *ConfigurationSystem `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{8}
}

func (x *Configuration) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Configuration) GetProjects() []*ConfigurationProject {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *Configuration) GetAi() *ConfigurationAI {
	if x != nil {
		return x.Ai
	}
	return nil
}

func (x *Configuration) GetSystem() *ConfigurationSystem {
	if x != nil {
		return x.System
	}
	return nil
}

type ConfigurationSystem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the UI can update configuration (true in desktop app, false in web server)
	CanUpdateConfiguration bool `protobuf:"varint,1,opt,name=can_update_configuration,json=canUpdateConfiguration,proto3" json:"can_update_configuration,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfigurationSystem) Reset() {
	*x = ConfigurationSystem{}
	mi := &file_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationSystem) ProtoMessage() {}

func (x *ConfigurationSystem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationSystem.ProtoReflect.Descriptor instead.
func (*ConfigurationSystem) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigurationSystem) GetCanUpdateConfiguration() bool {
	if x != nil {
		return x.CanUpdateConfiguration
	}
	return false
}

type ConfigurationProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      RpcProtocol            `protobuf:"varint,2,opt,name=protocol,proto3,enum=RpcProtocol" json:"protocol,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	ProtoDir      string                 `protobuf:"bytes,4,opt,name=proto_dir,json=protoDir,proto3" json:"proto_dir,omitempty"`
	UseReflection bool                   `protobuf:"varint,5,opt,name=use_reflection,json=useReflection,proto3" json:"use_reflection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationProject) Reset() {
	*x = ConfigurationProject{}
	mi := &file_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationProject) ProtoMessage() {}

func (x *ConfigurationProject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationProject.ProtoReflect.Descriptor instead.
func (*ConfigurationProject) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigurationProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigurationProject) GetProtocol() RpcProtocol {
	if x != nil {
		return x.Protocol
	}
	return RpcProtocol_RPC_PROTOCOL_TWIRP
}

func (x *ConfigurationProject) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ConfigurationProject) GetProtoDir() string {
	if x != nil {
		return x.ProtoDir
	}
	return ""
}

func (x *ConfigurationProject) GetUseReflection() bool {
	if x != nil {
		return x.UseReflection
	}
	return false
}

type ConfigurationAI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationAI) Reset() {
	*x = ConfigurationAI{}
	mi := &file_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationAI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationAI) ProtoMessage() {}

func (x *ConfigurationAI) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationAI.ProtoReflect.Descriptor instead.
func (*ConfigurationAI) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigurationAI) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ConfigurationAI) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type UpdateConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *Configuration         `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigurationRequest) Reset() {
	*x = UpdateConfigurationRequest{}
	mi := &file_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigurationRequest) ProtoMessage() {}

func (x *UpdateConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigurationRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateConfigurationRequest) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type UpdateConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *Configuration         `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigurationResponse) Reset() {
	*x = UpdateConfigurationResponse{}
	mi := &file_proto_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigurationResponse) ProtoMessage() {}

func (x *UpdateConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigurationResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateConfigurationResponse) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type ChatCompletionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopP          float64                `protobuf:"fixed64,4,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Stop          []string               `protobuf:"bytes,6,rep,name=stop,proto3" json:"stop,omitempty"` // Stop sequences to halt generation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionsRequest) Reset() {
	*x = ChatCompletionsRequest{}
	mi := &file_proto_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionsRequest) ProtoMessage() {}

func (x *ChatCompletionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionsRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{14}
}

func (x *ChatCompletionsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionsRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatCompletionsRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatCompletionsRequest) GetTopP() float64 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *ChatCompletionsRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatCompletionsRequest) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "system", "user", "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{15}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatCompletionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Choices       []*ChatChoice          `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	Usage         *ChatUsage             `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // Non-empty if there was an error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionsResponse) Reset() {
	*x = ChatCompletionsResponse{}
	mi := &file_proto_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionsResponse) ProtoMessage() {}

func (x *ChatCompletionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionsResponse.ProtoReflect.Descriptor instead.
func (*ChatCompletionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{16}
}

func (x *ChatCompletionsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionsResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionsResponse) GetChoices() []*ChatChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionsResponse) GetUsage() *ChatUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ChatCompletionsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ChatChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message       *ChatMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"` // "stop", "length", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChoice) Reset() {
	*x = ChatChoice{}
	mi := &file_proto_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChoice) ProtoMessage() {}

func (x *ChatChoice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChoice.ProtoReflect.Descriptor instead.
func (*ChatChoice) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{17}
}

func (x *ChatChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatChoice) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatChoice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type ChatUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatUsage) Reset() {
	*x = ChatUsage{}
	mi := &file_proto_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUsage) ProtoMessage() {}

func (x *ChatUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUsage.ProtoReflect.Descriptor instead.
func (*ChatUsage) Descriptor() ([]byte, []int) {
	return file_proto_api_proto_rawDescGZIP(), []int{18}
}

func (x *ChatUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ChatUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *ChatUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

var File_proto_api_proto protoreflect.FileDescriptor

const file_proto_api_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/api.proto\"\\\n" +
	"\x0eCompileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"log_offset\x18\x02 \x01(\x05R\tlogOffset\x12\x1b\n" +
	"\tproto_dir\x18\x03 \x01(\tR\bprotoDir\"\"\n" +
	"\x0eReflectRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"p\n" +
	"\x0fReflectResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.ReflectStatusR\x06status\x12\x18\n" +
	"\x04logs\x18\x02 \x03(\v2\x04.LogR\x04logs\x12\x1b\n" +
	"\tproto_dir\x18\x03 \x01(\tR\bprotoDir\"\x8a\x01\n" +
	"\x0fCompileResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.CompileStatusR\x06status\x12\x18\n" +
	"\x04logs\x18\x02 \x03(\v2\x04.LogR\x04logs\x12!\n" +
	"\asources\x18\x03 \x03(\v2\a.SourceR\asources\x12\x12\n" +
	"\x04stub\x18\x04 \x01(\tR\x04stub\"@\n" +
	"\x03Log\x12\x1f\n" +
	"\x05level\x18\x01 \x01(\x0e2\t.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"6\n" +
	"\x06Source\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x19\n" +
	"\x17GetConfigurationRequest\"j\n" +
	"\x18GetConfigurationResponse\x124\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x0e.ConfigurationR\rconfiguration\x12\x18\n" +
	"\x04logs\x18\x02 \x03(\v2\x04.LogR\x04logs\"\xb3\x01\n" +
	"\rConfiguration\x12\x1f\n" +
	"\vpath_prefix\x18\x01 \x01(\tR\n" +
	"pathPrefix\x121\n" +
	"\bprojects\x18\x02 \x03(\v2\x15.ConfigurationProjectR\bprojects\x12 \n" +
	"\x02ai\x18\x03 \x01(\v2\x10.ConfigurationAIR\x02ai\x12,\n" +
	"\x06system\x18\x04 \x01(\v2\x14.ConfigurationSystemR\x06system\"O\n" +
	"\x13ConfigurationSystem\x128\n" +
	"\x18can_update_configuration\x18\x01 \x01(\bR\x16canUpdateConfiguration\"\xaa\x01\n" +
	"\x14ConfigurationProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\f.RpcProtocolR\bprotocol\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1b\n" +
	"\tproto_dir\x18\x04 \x01(\tR\bprotoDir\x12%\n" +
	"\x0euse_reflection\x18\x05 \x01(\bR\ruseReflection\"E\n" +
	"\x0fConfigurationAI\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"R\n" +
	"\x1aUpdateConfigurationRequest\x124\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x0e.ConfigurationR\rconfiguration\"S\n" +
	"\x1bUpdateConfigurationResponse\x124\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x0e.ConfigurationR\rconfiguration\"\xc2\x01\n" +
	"\x16ChatCompletionsRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12(\n" +
	"\bmessages\x18\x02 \x03(\v2\f.ChatMessageR\bmessages\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x13\n" +
	"\x05top_p\x18\x04 \x01(\x01R\x04topP\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12\x12\n" +
	"\x04stop\x18\x06 \x03(\tR\x04stop\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x9e\x01\n" +
	"\x17ChatCompletionsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12%\n" +
	"\achoices\x18\x03 \x03(\v2\v.ChatChoiceR\achoices\x12 \n" +
	"\x05usage\x18\x04 \x01(\v2\n" +
	".ChatUsageR\x05usage\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"o\n" +
	"\n" +
	"ChatChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12&\n" +
	"\amessage\x18\x02 \x01(\v2\f.ChatMessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"\x80\x01\n" +
	"\tChatUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens*\\\n" +
	"\rReflectStatus\x12\x1a\n" +
	"\x16REFLECT_STATUS_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11REFLECT_STATUS_OK\x10\x01\x12\x18\n" +
	"\x14REFLECT_STATUS_ERROR\x10\x02*[\n" +
	"\rCompileStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x10\n" +
	"\fSTATUS_READY\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x02\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x03*L\n" +
	"\bLogLevel\x12\x0f\n" +
	"\vLEVEL_DEBUG\x10\x00\x12\x0e\n" +
	"\n" +
	"LEVEL_INFO\x10\x01\x12\x0e\n" +
	"\n" +
	"LEVEL_WARN\x10\x02\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x03*<\n" +
	"\vRpcProtocol\x12\x16\n" +
	"\x12RPC_PROTOCOL_TWIRP\x10\x00\x12\x15\n" +
	"\x11RPC_PROTOCOL_GRPC\x10\x012\xc2\x02\n" +
	"\x03Api\x12,\n" +
	"\aCompile\x12\x0f.CompileRequest\x1a\x10.CompileResponse\x12,\n" +
	"\aReflect\x12\x0f.ReflectRequest\x1a\x10.ReflectResponse\x12G\n" +
	"\x10GetConfiguration\x12\x18.GetConfigurationRequest\x1a\x19.GetConfigurationResponse\x12P\n" +
	"\x13UpdateConfiguration\x12\x1b.UpdateConfigurationRequest\x1a\x1c.UpdateConfigurationResponse\x12D\n" +
	"\x0fChatCompletions\x12\x17.ChatCompletionsRequest\x1a\x18.ChatCompletionsResponseB\tZ\apkg/apib\x06proto3"

var (
	file_proto_api_proto_rawDescOnce sync.Once
	file_proto_api_proto_rawDescData []byte
)

func file_proto_api_proto_rawDescGZIP() []byte {
	file_proto_api_proto_rawDescOnce.Do(func() {
		file_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)))
	})
	return file_proto_api_proto_rawDescData
}

var file_proto_api_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_api_proto_goTypes = []any{
	(ReflectStatus)(0),                  // 0: ReflectStatus
	(CompileStatus)(0),                  // 1: CompileStatus
	(LogLevel)(0),                       // 2: LogLevel
	(RpcProtocol)(0),                    // 3: RpcProtocol
	(*CompileRequest)(nil),              // 4: CompileRequest
	(*ReflectRequest)(nil),              // 5: ReflectRequest
	(*ReflectResponse)(nil),             // 6: ReflectResponse
	(*CompileResponse)(nil),             // 7: CompileResponse
	(*Log)(nil),                         // 8: Log
	(*Source)(nil),                      // 9: Source
	(*GetConfigurationRequest)(nil),     // 10: GetConfigurationRequest
	(*GetConfigurationResponse)(nil),    // 11: GetConfigurationResponse
	(*Configuration)(nil),               // 12: Configuration
	(*ConfigurationSystem)(nil),         // 13: ConfigurationSystem
	(*ConfigurationProject)(nil),        // 14: ConfigurationProject
	(*ConfigurationAI)(nil),             // 15: ConfigurationAI
	(*UpdateConfigurationRequest)(nil),  // 16: UpdateConfigurationRequest
	(*UpdateConfigurationResponse)(nil), // 17: UpdateConfigurationResponse
	(*ChatCompletionsRequest)(nil),      // 18: ChatCompletionsRequest
	(*ChatMessage)(nil),                 // 19: ChatMessage
	(*ChatCompletionsResponse)(nil),     // 20: ChatCompletionsResponse
	(*ChatChoice)(nil),                  // 21: ChatChoice
	(*ChatUsage)(nil),                   // 22: ChatUsage
}
var file_proto_api_proto_depIdxs = []int32{
	0,  // 0: ReflectResponse.status:type_name -> ReflectStatus
	8,  // 1: ReflectResponse.logs:type_name -> Log
	1,  // 2: CompileResponse.status:type_name -> CompileStatus
	8,  // 3: CompileResponse.logs:type_name -> Log
	9,  // 4: CompileResponse.sources:type_name -> Source
	2,  // 5: Log.level:type_name -> LogLevel
	12, // 6: GetConfigurationResponse.configuration:type_name -> Configuration
	8,  // 7: GetConfigurationResponse.logs:type_name -> Log
	14, // 8: Configuration.projects:type_name -> ConfigurationProject
	15, // 9: Configuration.ai:type_name -> ConfigurationAI
	13, // 10: Configuration.system:type_name -> ConfigurationSystem
	3,  // 11: ConfigurationProject.protocol:type_name -> RpcProtocol
	12, // 12: UpdateConfigurationRequest.configuration:type_name -> Configuration
	12, // 13: UpdateConfigurationResponse.configuration:type_name -> Configuration
	19, // 14: ChatCompletionsRequest.messages:type_name -> ChatMessage
	21, // 15: ChatCompletionsResponse.choices:type_name -> ChatChoice
	22, // 16: ChatCompletionsResponse.usage:type_name -> ChatUsage
	19, // 17: ChatChoice.message:type_name -> ChatMessage
	4,  // 18: Api.Compile:input_type -> CompileRequest
	5,  // 19: Api.Reflect:input_type -> ReflectRequest
	10, // 20: Api.GetConfiguration:input_type -> GetConfigurationRequest
	16, // 21: Api.UpdateConfiguration:input_type -> UpdateConfigurationRequest
	18, // 22: Api.ChatCompletions:input_type -> ChatCompletionsRequest
	7,  // 23: Api.Compile:output_type -> CompileResponse
	6,  // 24: Api.Reflect:output_type -> ReflectResponse
	11, // 25: Api.GetConfiguration:output_type -> GetConfigurationResponse
	17, // 26: Api.UpdateConfiguration:output_type -> UpdateConfigurationResponse
	20, // 27: Api.ChatCompletions:output_type -> ChatCompletionsResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_api_proto_init() }
func file_proto_api_proto_init() {
	if File_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_proto_rawDesc), len(file_proto_api_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_proto_goTypes,
		DependencyIndexes: file_proto_api_proto_depIdxs,
		EnumInfos:         file_proto_api_proto_enumTypes,
		MessageInfos:      file_proto_api_proto_msgTypes,
	}.Build()
	File_proto_api_proto = out.File
	file_proto_api_proto_goTypes = nil
	file_proto_api_proto_depIdxs = nil
}
