// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Api_Compile_FullMethodName             = "/Api/Compile"
	Api_OpenApp_FullMethodName             = "/Api/OpenApp"
	Api_InspectOpenApi_FullMethodName      = "/Api/InspectOpenApi"
	Api_InspectGrpc_FullMethodName         = "/Api/InspectGrpc"
	Api_InspectMcp_FullMethodName          = "/Api/InspectMcp"
	Api_GetConfiguration_FullMethodName    = "/Api/GetConfiguration"
	Api_WatchConfiguration_FullMethodName  = "/Api/WatchConfiguration"
	Api_UpdateConfiguration_FullMethodName = "/Api/UpdateConfiguration"
	Api_SetStoredValue_FullMethodName      = "/Api/SetStoredValue"
	Api_ClearStoredValue_FullMethodName    = "/Api/ClearStoredValue"
	Api_ListScripts_FullMethodName         = "/Api/ListScripts"
	Api_ReadScript_FullMethodName          = "/Api/ReadScript"
	Api_WriteScript_FullMethodName         = "/Api/WriteScript"
	Api_CreateScript_FullMethodName        = "/Api/CreateScript"
	Api_RenameScript_FullMethodName        = "/Api/RenameScript"
	Api_DeleteScript_FullMethodName        = "/Api/DeleteScript"
	Api_ListScriptFolders_FullMethodName   = "/Api/ListScriptFolders"
	Api_CreateScriptFolder_FullMethodName  = "/Api/CreateScriptFolder"
	Api_RenameScriptFolder_FullMethodName  = "/Api/RenameScriptFolder"
	Api_DeleteScriptFolder_FullMethodName  = "/Api/DeleteScriptFolder"
)

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	// Compile streams the compilation of an app's proto surface: each log line as it
	// is written, then one last message carrying the terminal status and, on success,
	// the generated sources and the stub.
	Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompileResponse], error)
	OpenApp(ctx context.Context, in *OpenAppRequest, opts ...grpc.CallOption) (*OpenAppResponse, error)
	InspectOpenApi(ctx context.Context, in *InspectOpenApiRequest, opts ...grpc.CallOption) (*InspectOpenApiResponse, error)
	InspectGrpc(ctx context.Context, in *InspectGrpcRequest, opts ...grpc.CallOption) (*InspectGrpcResponse, error)
	InspectMcp(ctx context.Context, in *InspectMcpRequest, opts ...grpc.CallOption) (*InspectMcpResponse, error)
	GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error)
	// WatchConfiguration streams the configuration file as it is edited: one message
	// carrying the whole configuration each time the file changes. What changed is
	// never asked for afterwards, because the message is the new configuration.
	WatchConfiguration(ctx context.Context, in *WatchConfigurationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetConfigurationResponse], error)
	UpdateConfiguration(ctx context.Context, in *UpdateConfigurationRequest, opts ...grpc.CallOption) (*UpdateConfigurationResponse, error)
	SetStoredValue(ctx context.Context, in *SetStoredValueRequest, opts ...grpc.CallOption) (*StoredValueResponse, error)
	ClearStoredValue(ctx context.Context, in *ClearStoredValueRequest, opts ...grpc.CallOption) (*StoredValueResponse, error)
	ListScripts(ctx context.Context, in *ListScriptsRequest, opts ...grpc.CallOption) (*ListScriptsResponse, error)
	ReadScript(ctx context.Context, in *ReadScriptRequest, opts ...grpc.CallOption) (*ReadScriptResponse, error)
	WriteScript(ctx context.Context, in *WriteScriptRequest, opts ...grpc.CallOption) (*WriteScriptResponse, error)
	CreateScript(ctx context.Context, in *CreateScriptRequest, opts ...grpc.CallOption) (*CreateScriptResponse, error)
	RenameScript(ctx context.Context, in *RenameScriptRequest, opts ...grpc.CallOption) (*RenameScriptResponse, error)
	DeleteScript(ctx context.Context, in *DeleteScriptRequest, opts ...grpc.CallOption) (*DeleteScriptResponse, error)
	ListScriptFolders(ctx context.Context, in *ListScriptFoldersRequest, opts ...grpc.CallOption) (*ListScriptFoldersResponse, error)
	CreateScriptFolder(ctx context.Context, in *CreateScriptFolderRequest, opts ...grpc.CallOption) (*CreateScriptFolderResponse, error)
	RenameScriptFolder(ctx context.Context, in *RenameScriptFolderRequest, opts ...grpc.CallOption) (*RenameScriptFolderResponse, error)
	DeleteScriptFolder(ctx context.Context, in *DeleteScriptFolderRequest, opts ...grpc.CallOption) (*DeleteScriptFolderResponse, error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[0], Api_Compile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompileRequest, CompileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_CompileClient = grpc.ServerStreamingClient[CompileResponse]

func (c *apiClient) OpenApp(ctx context.Context, in *OpenAppRequest, opts ...grpc.CallOption) (*OpenAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenAppResponse)
	err := c.cc.Invoke(ctx, Api_OpenApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) InspectOpenApi(ctx context.Context, in *InspectOpenApiRequest, opts ...grpc.CallOption) (*InspectOpenApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectOpenApiResponse)
	err := c.cc.Invoke(ctx, Api_InspectOpenApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) InspectGrpc(ctx context.Context, in *InspectGrpcRequest, opts ...grpc.CallOption) (*InspectGrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectGrpcResponse)
	err := c.cc.Invoke(ctx, Api_InspectGrpc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) InspectMcp(ctx context.Context, in *InspectMcpRequest, opts ...grpc.CallOption) (*InspectMcpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectMcpResponse)
	err := c.cc.Invoke(ctx, Api_InspectMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigurationResponse)
	err := c.cc.Invoke(ctx, Api_GetConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) WatchConfiguration(ctx context.Context, in *WatchConfigurationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetConfigurationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[1], Api_WatchConfiguration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchConfigurationRequest, GetConfigurationResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_WatchConfigurationClient = grpc.ServerStreamingClient[GetConfigurationResponse]

func (c *apiClient) UpdateConfiguration(ctx context.Context, in *UpdateConfigurationRequest, opts ...grpc.CallOption) (*UpdateConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigurationResponse)
	err := c.cc.Invoke(ctx, Api_UpdateConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SetStoredValue(ctx context.Context, in *SetStoredValueRequest, opts ...grpc.CallOption) (*StoredValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoredValueResponse)
	err := c.cc.Invoke(ctx, Api_SetStoredValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ClearStoredValue(ctx context.Context, in *ClearStoredValueRequest, opts ...grpc.CallOption) (*StoredValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoredValueResponse)
	err := c.cc.Invoke(ctx, Api_ClearStoredValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ListScripts(ctx context.Context, in *ListScriptsRequest, opts ...grpc.CallOption) (*ListScriptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScriptsResponse)
	err := c.cc.Invoke(ctx, Api_ListScripts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ReadScript(ctx context.Context, in *ReadScriptRequest, opts ...grpc.CallOption) (*ReadScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadScriptResponse)
	err := c.cc.Invoke(ctx, Api_ReadScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) WriteScript(ctx context.Context, in *WriteScriptRequest, opts ...grpc.CallOption) (*WriteScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteScriptResponse)
	err := c.cc.Invoke(ctx, Api_WriteScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) CreateScript(ctx context.Context, in *CreateScriptRequest, opts ...grpc.CallOption) (*CreateScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateScriptResponse)
	err := c.cc.Invoke(ctx, Api_CreateScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RenameScript(ctx context.Context, in *RenameScriptRequest, opts ...grpc.CallOption) (*RenameScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameScriptResponse)
	err := c.cc.Invoke(ctx, Api_RenameScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) DeleteScript(ctx context.Context, in *DeleteScriptRequest, opts ...grpc.CallOption) (*DeleteScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteScriptResponse)
	err := c.cc.Invoke(ctx, Api_DeleteScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) ListScriptFolders(ctx context.Context, in *ListScriptFoldersRequest, opts ...grpc.CallOption) (*ListScriptFoldersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScriptFoldersResponse)
	err := c.cc.Invoke(ctx, Api_ListScriptFolders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) CreateScriptFolder(ctx context.Context, in *CreateScriptFolderRequest, opts ...grpc.CallOption) (*CreateScriptFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateScriptFolderResponse)
	err := c.cc.Invoke(ctx, Api_CreateScriptFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RenameScriptFolder(ctx context.Context, in *RenameScriptFolderRequest, opts ...grpc.CallOption) (*RenameScriptFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameScriptFolderResponse)
	err := c.cc.Invoke(ctx, Api_RenameScriptFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) DeleteScriptFolder(ctx context.Context, in *DeleteScriptFolderRequest, opts ...grpc.CallOption) (*DeleteScriptFolderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteScriptFolderResponse)
	err := c.cc.Invoke(ctx, Api_DeleteScriptFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServer is the server API for Api service.
// All implementations should embed UnimplementedApiServer
// for forward compatibility.
type ApiServer interface {
	// Compile streams the compilation of an app's proto surface: each log line as it
	// is written, then one last message carrying the terminal status and, on success,
	// the generated sources and the stub.
	Compile(*CompileRequest, grpc.ServerStreamingServer[CompileResponse]) error
	OpenApp(context.Context, *OpenAppRequest) (*OpenAppResponse, error)
	InspectOpenApi(context.Context, *InspectOpenApiRequest) (*InspectOpenApiResponse, error)
	InspectGrpc(context.Context, *InspectGrpcRequest) (*InspectGrpcResponse, error)
	InspectMcp(context.Context, *InspectMcpRequest) (*InspectMcpResponse, error)
	GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error)
	// WatchConfiguration streams the configuration file as it is edited: one message
	// carrying the whole configuration each time the file changes. What changed is
	// never asked for afterwards, because the message is the new configuration.
	WatchConfiguration(*WatchConfigurationRequest, grpc.ServerStreamingServer[GetConfigurationResponse]) error
	UpdateConfiguration(context.Context, *UpdateConfigurationRequest) (*UpdateConfigurationResponse, error)
	SetStoredValue(context.Context, *SetStoredValueRequest) (*StoredValueResponse, error)
	ClearStoredValue(context.Context, *ClearStoredValueRequest) (*StoredValueResponse, error)
	ListScripts(context.Context, *ListScriptsRequest) (*ListScriptsResponse, error)
	ReadScript(context.Context, *ReadScriptRequest) (*ReadScriptResponse, error)
	WriteScript(context.Context, *WriteScriptRequest) (*WriteScriptResponse, error)
	CreateScript(context.Context, *CreateScriptRequest) (*CreateScriptResponse, error)
	RenameScript(context.Context, *RenameScriptRequest) (*RenameScriptResponse, error)
	DeleteScript(context.Context, *DeleteScriptRequest) (*DeleteScriptResponse, error)
	ListScriptFolders(context.Context, *ListScriptFoldersRequest) (*ListScriptFoldersResponse, error)
	CreateScriptFolder(context.Context, *CreateScriptFolderRequest) (*CreateScriptFolderResponse, error)
	RenameScriptFolder(context.Context, *RenameScriptFolderRequest) (*RenameScriptFolderResponse, error)
	DeleteScriptFolder(context.Context, *DeleteScriptFolderRequest) (*DeleteScriptFolderResponse, error)
}

// UnimplementedApiServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServer struct{}

func (UnimplementedApiServer) Compile(*CompileRequest, grpc.ServerStreamingServer[CompileResponse]) error {
	return status.Error(codes.Unimplemented, "method Compile not implemented")
}
func (UnimplementedApiServer) OpenApp(context.Context, *OpenAppRequest) (*OpenAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenApp not implemented")
}
func (UnimplementedApiServer) InspectOpenApi(context.Context, *InspectOpenApiRequest) (*InspectOpenApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectOpenApi not implemented")
}
func (UnimplementedApiServer) InspectGrpc(context.Context, *InspectGrpcRequest) (*InspectGrpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectGrpc not implemented")
}
func (UnimplementedApiServer) InspectMcp(context.Context, *InspectMcpRequest) (*InspectMcpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectMcp not implemented")
}
func (UnimplementedApiServer) GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedApiServer) WatchConfiguration(*WatchConfigurationRequest, grpc.ServerStreamingServer[GetConfigurationResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchConfiguration not implemented")
}
func (UnimplementedApiServer) UpdateConfiguration(context.Context, *UpdateConfigurationRequest) (*UpdateConfigurationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfiguration not implemented")
}
func (UnimplementedApiServer) SetStoredValue(context.Context, *SetStoredValueRequest) (*StoredValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStoredValue not implemented")
}
func (UnimplementedApiServer) ClearStoredValue(context.Context, *ClearStoredValueRequest) (*StoredValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearStoredValue not implemented")
}
func (UnimplementedApiServer) ListScripts(context.Context, *ListScriptsRequest) (*ListScriptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScripts not implemented")
}
func (UnimplementedApiServer) ReadScript(context.Context, *ReadScriptRequest) (*ReadScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadScript not implemented")
}
func (UnimplementedApiServer) WriteScript(context.Context, *WriteScriptRequest) (*WriteScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteScript not implemented")
}
func (UnimplementedApiServer) CreateScript(context.Context, *CreateScriptRequest) (*CreateScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateScript not implemented")
}
func (UnimplementedApiServer) RenameScript(context.Context, *RenameScriptRequest) (*RenameScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameScript not implemented")
}
func (UnimplementedApiServer) DeleteScript(context.Context, *DeleteScriptRequest) (*DeleteScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteScript not implemented")
}
func (UnimplementedApiServer) ListScriptFolders(context.Context, *ListScriptFoldersRequest) (*ListScriptFoldersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScriptFolders not implemented")
}
func (UnimplementedApiServer) CreateScriptFolder(context.Context, *CreateScriptFolderRequest) (*CreateScriptFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateScriptFolder not implemented")
}
func (UnimplementedApiServer) RenameScriptFolder(context.Context, *RenameScriptFolderRequest) (*RenameScriptFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameScriptFolder not implemented")
}
func (UnimplementedApiServer) DeleteScriptFolder(context.Context, *DeleteScriptFolderRequest) (*DeleteScriptFolderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteScriptFolder not implemented")
}
func (UnimplementedApiServer) testEmbeddedByValue() {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	// If the following call panics, it indicates UnimplementedApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_Compile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).Compile(m, &grpc.GenericServerStream[CompileRequest, CompileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_CompileServer = grpc.ServerStreamingServer[CompileResponse]

func _Api_OpenApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).OpenApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_OpenApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).OpenApp(ctx, req.(*OpenAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_InspectOpenApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectOpenApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).InspectOpenApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_InspectOpenApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).InspectOpenApi(ctx, req.(*InspectOpenApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_InspectGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).InspectGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_InspectGrpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).InspectGrpc(ctx, req.(*InspectGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_InspectMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectMcpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).InspectMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_InspectMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).InspectMcp(ctx, req.(*InspectMcpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetConfiguration(ctx, req.(*GetConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_WatchConfiguration_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchConfigurationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).WatchConfiguration(m, &grpc.GenericServerStream[WatchConfigurationRequest, GetConfigurationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_WatchConfigurationServer = grpc.ServerStreamingServer[GetConfigurationResponse]

func _Api_UpdateConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).UpdateConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_UpdateConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).UpdateConfiguration(ctx, req.(*UpdateConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SetStoredValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStoredValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).SetStoredValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_SetStoredValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).SetStoredValue(ctx, req.(*SetStoredValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ClearStoredValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearStoredValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ClearStoredValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_ClearStoredValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ClearStoredValue(ctx, req.(*ClearStoredValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ListScripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScriptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ListScripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_ListScripts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ListScripts(ctx, req.(*ListScriptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ReadScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ReadScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_ReadScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ReadScript(ctx, req.(*ReadScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_WriteScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).WriteScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_WriteScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).WriteScript(ctx, req.(*WriteScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_CreateScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).CreateScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_CreateScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).CreateScript(ctx, req.(*CreateScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RenameScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RenameScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_RenameScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RenameScript(ctx, req.(*RenameScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_DeleteScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).DeleteScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_DeleteScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).DeleteScript(ctx, req.(*DeleteScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_ListScriptFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScriptFoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).ListScriptFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_ListScriptFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).ListScriptFolders(ctx, req.(*ListScriptFoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_CreateScriptFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScriptFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).CreateScriptFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_CreateScriptFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).CreateScriptFolder(ctx, req.(*CreateScriptFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RenameScriptFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameScriptFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RenameScriptFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_RenameScriptFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RenameScriptFolder(ctx, req.(*RenameScriptFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_DeleteScriptFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScriptFolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).DeleteScriptFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_DeleteScriptFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).DeleteScriptFolder(ctx, req.(*DeleteScriptFolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenApp",
			Handler:    _Api_OpenApp_Handler,
		},
		{
			MethodName: "InspectOpenApi",
			Handler:    _Api_InspectOpenApi_Handler,
		},
		{
			MethodName: "InspectGrpc",
			Handler:    _Api_InspectGrpc_Handler,
		},
		{
			MethodName: "InspectMcp",
			Handler:    _Api_InspectMcp_Handler,
		},
		{
			MethodName: "GetConfiguration",
			Handler:    _Api_GetConfiguration_Handler,
		},
		{
			MethodName: "UpdateConfiguration",
			Handler:    _Api_UpdateConfiguration_Handler,
		},
		{
			MethodName: "SetStoredValue",
			Handler:    _Api_SetStoredValue_Handler,
		},
		{
			MethodName: "ClearStoredValue",
			Handler:    _Api_ClearStoredValue_Handler,
		},
		{
			MethodName: "ListScripts",
			Handler:    _Api_ListScripts_Handler,
		},
		{
			MethodName: "ReadScript",
			Handler:    _Api_ReadScript_Handler,
		},
		{
			MethodName: "WriteScript",
			Handler:    _Api_WriteScript_Handler,
		},
		{
			MethodName: "CreateScript",
			Handler:    _Api_CreateScript_Handler,
		},
		{
			MethodName: "RenameScript",
			Handler:    _Api_RenameScript_Handler,
		},
		{
			MethodName: "DeleteScript",
			Handler:    _Api_DeleteScript_Handler,
		},
		{
			MethodName: "ListScriptFolders",
			Handler:    _Api_ListScriptFolders_Handler,
		},
		{
			MethodName: "CreateScriptFolder",
			Handler:    _Api_CreateScriptFolder_Handler,
		},
		{
			MethodName: "RenameScriptFolder",
			Handler:    _Api_RenameScriptFolder_Handler,
		},
		{
			MethodName: "DeleteScriptFolder",
			Handler:    _Api_DeleteScriptFolder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Compile",
			Handler:       _Api_Compile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchConfiguration",
			Handler:       _Api_WatchConfiguration_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/api.proto",
}
