// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "api.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Api } from "./api";
import type { ChatCompletionsResponse } from "./api";
import type { ChatCompletionsRequest } from "./api";
import type { UpdateConfigurationResponse } from "./api";
import type { UpdateConfigurationRequest } from "./api";
import type { GetConfigurationResponse } from "./api";
import type { GetConfigurationRequest } from "./api";
import type { ReflectResponse } from "./api";
import type { ReflectRequest } from "./api";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CompileResponse } from "./api";
import type { CompileRequest } from "./api";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service Api
 */
export interface IApiClient {
    /**
     * @generated from protobuf rpc: Compile
     */
    compile(input: CompileRequest, options?: RpcOptions): UnaryCall<CompileRequest, CompileResponse>;
    /**
     * @generated from protobuf rpc: Reflect
     */
    reflect(input: ReflectRequest, options?: RpcOptions): UnaryCall<ReflectRequest, ReflectResponse>;
    /**
     * @generated from protobuf rpc: GetConfiguration
     */
    getConfiguration(input: GetConfigurationRequest, options?: RpcOptions): UnaryCall<GetConfigurationRequest, GetConfigurationResponse>;
    /**
     * @generated from protobuf rpc: UpdateConfiguration
     */
    updateConfiguration(input: UpdateConfigurationRequest, options?: RpcOptions): UnaryCall<UpdateConfigurationRequest, UpdateConfigurationResponse>;
    /**
     * @generated from protobuf rpc: ChatCompletions
     */
    chatCompletions(input: ChatCompletionsRequest, options?: RpcOptions): UnaryCall<ChatCompletionsRequest, ChatCompletionsResponse>;
}
/**
 * @generated from protobuf service Api
 */
export class ApiClient implements IApiClient, ServiceInfo {
    typeName = Api.typeName;
    methods = Api.methods;
    options = Api.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Compile
     */
    compile(input: CompileRequest, options?: RpcOptions): UnaryCall<CompileRequest, CompileResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CompileRequest, CompileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Reflect
     */
    reflect(input: ReflectRequest, options?: RpcOptions): UnaryCall<ReflectRequest, ReflectResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReflectRequest, ReflectResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetConfiguration
     */
    getConfiguration(input: GetConfigurationRequest, options?: RpcOptions): UnaryCall<GetConfigurationRequest, GetConfigurationResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetConfigurationRequest, GetConfigurationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateConfiguration
     */
    updateConfiguration(input: UpdateConfigurationRequest, options?: RpcOptions): UnaryCall<UpdateConfigurationRequest, UpdateConfigurationResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateConfigurationRequest, UpdateConfigurationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ChatCompletions
     */
    chatCompletions(input: ChatCompletionsRequest, options?: RpcOptions): UnaryCall<ChatCompletionsRequest, ChatCompletionsResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChatCompletionsRequest, ChatCompletionsResponse>("unary", this._transport, method, opt, input);
    }
}
