// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_optimize_code_size
// @generated from protobuf file "api.proto" (syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message CompileRequest
 */
export interface CompileRequest {
    /**
     * @generated from protobuf field: string proto_dir = 1
     */
    protoDir: string;
}
/**
 * OpenApp opens an app from its configuration. A "grpc" app describes a gRPC
 * service (proto files come from a static directory or gRPC reflection), while every
 * other app generates its own proto surface. In all cases the app produces proto
 * files to feed into Compile and an invocation target. The server flattens the app's
 * typed parameters to a string map for the in-process app contract.
 *
 * @generated from protobuf message OpenAppRequest
 */
export interface OpenAppRequest {
    /**
     * @generated from protobuf field: ConfigurationApp app = 1
     */
    app?: ConfigurationApp;
}
/**
 * @generated from protobuf message OpenAppResponse
 */
export interface OpenAppResponse {
    /**
     * @generated from protobuf field: OpenStatus status = 1
     */
    status: OpenStatus;
    /**
     * @generated from protobuf field: repeated Log logs = 2
     */
    logs: Log[];
    /**
     * Directory containing the proto files to compile (only set on success). Either a
     * temp directory (generated/reflected protos) or a workspace-relative path (static
     * protos), which Compile resolves against the workspace.
     *
     * @generated from protobuf field: string proto_dir = 3
     */
    protoDir: string;
}
/**
 * InspectGrpc reads the service surface a grpc app *would* be opened with -
 * reflecting the server, or reading the proto directory - without creating the
 * app, so the New gRPC app form can fill itself in from what answered. The app
 * carries the same parameters the app would be opened with, credentials
 * included: a server may well ask for them before it reflects.
 *
 * @generated from protobuf message InspectGrpcRequest
 */
export interface InspectGrpcRequest {
    /**
     * @generated from protobuf field: GrpcApp grpc = 1
     */
    grpc?: GrpcApp;
}
/**
 * @generated from protobuf message InspectGrpcResponse
 */
export interface InspectGrpcResponse {
    /**
     * Set when the surface was read; the form fills itself in from it.
     *
     * @generated from protobuf field: GrpcServer server = 1
     */
    server?: GrpcServer;
    /**
     * Set when it wasn't; the form shows it in place of the summary.
     *
     * @generated from protobuf field: GrpcProblem problem = 2
     */
    problem?: GrpcProblem;
}
/**
 * @generated from protobuf message GrpcServer
 */
export interface GrpcServer {
    /**
     * Where the surface came from: "reflection" or "proto_dir".
     *
     * @generated from protobuf field: string source = 1
     */
    source: string;
    /**
     * The gRPC target that answered, e.g. "dns:seating.kaja.tools:443". Empty for
     * the proto_dir source, which reaches no server.
     *
     * @generated from protobuf field: string target = 2
     */
    target: string;
    /**
     * Whether the connection that answered used TLS. When the app leaves the
     * choice to the URL, this is what kaja settled on by trying, and the form
     * writes it back so the app says outright what it does.
     *
     * @generated from protobuf field: bool tls = 3
     */
    tls: boolean;
    /**
     * @generated from protobuf field: repeated GrpcService services = 4
     */
    services: GrpcService[];
    /**
     * @generated from protobuf field: int32 method_count = 5
     */
    methodCount: number;
    /**
     * The reflection API the server answered: "v1" or "v1alpha".
     *
     * @generated from protobuf field: string reflection_version = 6
     */
    reflectionVersion: string;
    /**
     * Proto files read, for the proto_dir source.
     *
     * @generated from protobuf field: int32 file_count = 7
     */
    fileCount: number;
    /**
     * The directory the proto files were read from, resolved against the
     * workspace, for the proto_dir source.
     *
     * @generated from protobuf field: string proto_dir = 8
     */
    protoDir: string;
    /**
     * Whether the server answered at all. Always true for the reflection source,
     * which is nothing but the server answering; for the proto_dir source it is
     * the separate question of whether the address is live, which the proto files
     * can't say and which doesn't stop the app being configured.
     *
     * @generated from protobuf field: bool reachable = 9
     */
    reachable: boolean;
}
/**
 * @generated from protobuf message GrpcService
 */
export interface GrpcService {
    /**
     * Fully qualified name, e.g. "seating.Seating".
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: int32 method_count = 2
     */
    methodCount: number;
    /**
     * Methods that stream from the client, bidirectional ones included. Neither
     * build carries a stream in that direction, so they are listed but can't be
     * called; a stream from the server is carried on both.
     *
     * @generated from protobuf field: int32 client_streaming_method_count = 3
     */
    clientStreamingMethodCount: number;
}
/**
 * GrpcProblem is a surface that couldn't be read, classified so the form can
 * name the next move instead of printing a raw error.
 *
 * @generated from protobuf message GrpcProblem
 */
export interface GrpcProblem {
    /**
     * @generated from protobuf field: GrpcProblemKind kind = 1
     */
    kind: GrpcProblemKind;
    /**
     * One line, addressed to the user.
     *
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * The underlying transport, reflection or compiler error, verbatim.
     *
     * @generated from protobuf field: string detail = 3
     */
    detail: string;
}
/**
 * InspectOpenApi reads an OpenAPI document without creating an app, so the New
 * OpenAPI app form can fill itself in from the document: its title and version,
 * the servers it declares, and the security schemes it accepts. The app carries
 * the same parameters the app would be opened with (spec_url or spec_content, and
 * the credentials used to fetch a protected document).
 *
 * @generated from protobuf message InspectOpenApiRequest
 */
export interface InspectOpenApiRequest {
    /**
     * @generated from protobuf field: OpenApiApp openapi = 1
     */
    openapi?: OpenApiApp;
}
/**
 * @generated from protobuf message InspectOpenApiResponse
 */
export interface InspectOpenApiResponse {
    /**
     * Set when the document was read; the form fills itself in from it.
     *
     * @generated from protobuf field: OpenApiDocument document = 1
     */
    document?: OpenApiDocument;
    /**
     * Set when it wasn't; the form shows it in place of the document summary.
     *
     * @generated from protobuf field: OpenApiProblem problem = 2
     */
    problem?: OpenApiProblem;
}
/**
 * @generated from protobuf message OpenApiDocument
 */
export interface OpenApiDocument {
    /**
     * @generated from protobuf field: string title = 1
     */
    title: string;
    /**
     * The API's own version, from info.version.
     *
     * @generated from protobuf field: string version = 2
     */
    version: string;
    /**
     * The OpenAPI specification version, from the openapi field.
     *
     * @generated from protobuf field: string openapi_version = 3
     */
    openapiVersion: string;
    /**
     * @generated from protobuf field: int32 operation_count = 4
     */
    operationCount: number;
    /**
     * @generated from protobuf field: int32 tag_count = 5
     */
    tagCount: number;
    /**
     * @generated from protobuf field: repeated OpenApiServer servers = 6
     */
    servers: OpenApiServer[];
    /**
     * @generated from protobuf field: repeated OpenApiSecurityScheme security_schemes = 7
     */
    securitySchemes: OpenApiSecurityScheme[];
    /**
     * Base URL derived from the document URL's origin, set only when the document
     * declares no servers of its own.
     *
     * @generated from protobuf field: string guessed_base_url = 8
     */
    guessedBaseUrl: string;
    /**
     * Whether any operation declares its own security. When it doesn't, every
     * scheme applies to every operation and the coverage counts carry no
     * information.
     *
     * @generated from protobuf field: bool per_operation_security = 9
     */
    perOperationSecurity: boolean;
}
/**
 * @generated from protobuf message OpenApiServer
 */
export interface OpenApiServer {
    /**
     * @generated from protobuf field: string url = 1
     */
    url: string;
    /**
     * @generated from protobuf field: string description = 2
     */
    description: string;
    /**
     * @generated from protobuf field: repeated OpenApiServerVariable variables = 3
     */
    variables: OpenApiServerVariable[];
}
/**
 * OpenApiServerVariable is one {placeholder} in a server URL. The form renders a
 * select when the document enumerates the allowed values, and a text field
 * otherwise.
 *
 * @generated from protobuf message OpenApiServerVariable
 */
export interface OpenApiServerVariable {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string default_value = 2
     */
    defaultValue: string;
    /**
     * @generated from protobuf field: repeated string enum_values = 3
     */
    enumValues: string[];
    /**
     * @generated from protobuf field: string description = 4
     */
    description: string;
}
/**
 * @generated from protobuf message OpenApiSecurityScheme
 */
export interface OpenApiSecurityScheme {
    /**
     * Name of the scheme in components.securitySchemes; what security_scheme in
     * OpenApiApp refers to.
     *
     * @generated from protobuf field: string key = 1
     */
    key: string;
    /**
     * apiKey | http | oauth2 | openIdConnect | mutualTLS
     *
     * @generated from protobuf field: string type = 2
     */
    type: string;
    /**
     * The HTTP authentication scheme (bearer, basic, digest, ...) for type http.
     *
     * @generated from protobuf field: string scheme = 3
     */
    scheme: string;
    /**
     * @generated from protobuf field: string bearer_format = 4
     */
    bearerFormat: string;
    /**
     * header | query | cookie, for type apiKey.
     *
     * @generated from protobuf field: string in = 5
     */
    in: string;
    /**
     * Parameter name for type apiKey.
     *
     * @generated from protobuf field: string parameter_name = 6
     */
    parameterName: string;
    /**
     * @generated from protobuf field: string open_id_connect_url = 7
     */
    openIdConnectUrl: string;
    /**
     * @generated from protobuf field: string description = 8
     */
    description: string;
    /**
     * Number of operations that accept this scheme on its own.
     *
     * @generated from protobuf field: int32 operation_count = 9
     */
    operationCount: number;
    /**
     * Whether the scheme only ever appears alongside another one, which a single
     * credential per app can't satisfy.
     *
     * @generated from protobuf field: bool requires_others = 10
     */
    requiresOthers: boolean;
}
/**
 * OpenApiProblem is a document that couldn't be read, classified so the form can
 * name the next move instead of printing a raw error.
 *
 * @generated from protobuf message OpenApiProblem
 */
export interface OpenApiProblem {
    /**
     * @generated from protobuf field: OpenApiProblemKind kind = 1
     */
    kind: OpenApiProblemKind;
    /**
     * One line, addressed to the user.
     *
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * The underlying transport or parser error, verbatim.
     *
     * @generated from protobuf field: string detail = 3
     */
    detail: string;
}
/**
 * InspectMcp reads what an MCP server exposes without creating an app, so the
 * New MCP app form can fill itself in from what answered: the server's own name
 * and version, the protocol revision it speaks, and the tools, resources and
 * prompts it lists. The app carries the same parameters the app would be opened
 * with, credential included - an MCP server usually guards the list of its tools
 * as closely as the tools themselves.
 *
 * @generated from protobuf message InspectMcpRequest
 */
export interface InspectMcpRequest {
    /**
     * @generated from protobuf field: McpApp mcp = 1
     */
    mcp?: McpApp;
}
/**
 * @generated from protobuf message InspectMcpResponse
 */
export interface InspectMcpResponse {
    /**
     * Set when the server was read; the form fills itself in from it.
     *
     * @generated from protobuf field: McpServer server = 1
     */
    server?: McpServer;
    /**
     * Set when it wasn't; the form shows it in place of the summary.
     *
     * @generated from protobuf field: McpProblem problem = 2
     */
    problem?: McpProblem;
}
/**
 * @generated from protobuf message McpServer
 */
export interface McpServer {
    /**
     * What the server calls itself. Self-reported, and only ever displayed.
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string version = 2
     */
    version: string;
    /**
     * The protocol revision the exchange settled on, e.g. "2026-07-28".
     *
     * @generated from protobuf field: string protocol_version = 3
     */
    protocolVersion: string;
    /**
     * Whether the server opened with the `initialize` handshake rather than the
     * per-request metadata the protocol uses from 2026-07-28 on.
     *
     * @generated from protobuf field: bool handshake = 4
     */
    handshake: boolean;
    /**
     * Every revision the server says it speaks. Only a modern server reports this.
     *
     * @generated from protobuf field: repeated string supported_versions = 5
     */
    supportedVersions: string[];
    /**
     * @generated from protobuf field: int32 tool_count = 6
     */
    toolCount: number;
    /**
     * @generated from protobuf field: int32 resource_count = 7
     */
    resourceCount: number;
    /**
     * @generated from protobuf field: int32 resource_template_count = 8
     */
    resourceTemplateCount: number;
    /**
     * @generated from protobuf field: int32 prompt_count = 9
     */
    promptCount: number;
    /**
     * The tools it listed, so the form can show what the app would add.
     *
     * @generated from protobuf field: repeated McpTool tools = 10
     */
    tools: McpTool[];
    /**
     * The server's own guidance on how to use it, where it offers any.
     *
     * @generated from protobuf field: string instructions = 11
     */
    instructions: string;
}
/**
 * @generated from protobuf message McpTool
 */
export interface McpTool {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
    /**
     * The server's own hint that the tool only reads. It is the server's word and
     * nothing more.
     *
     * @generated from protobuf field: bool read_only = 4
     */
    readOnly: boolean;
}
/**
 * McpProblem is a server that couldn't be read, classified so the form can name
 * the next move instead of printing a raw error.
 *
 * @generated from protobuf message McpProblem
 */
export interface McpProblem {
    /**
     * @generated from protobuf field: McpProblemKind kind = 1
     */
    kind: McpProblemKind;
    /**
     * One line, addressed to the user.
     *
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * The underlying transport or protocol error, verbatim.
     *
     * @generated from protobuf field: string detail = 3
     */
    detail: string;
}
/**
 * CompileResponse is one message of the compilation's stream. A STATUS_RUNNING
 * message carries the log lines written since the last one and nothing else; the
 * last message of a stream is the terminal status, with the sources and the stub
 * on a STATUS_READY.
 *
 * @generated from protobuf message CompileResponse
 */
export interface CompileResponse {
    /**
     * @generated from protobuf field: CompileStatus status = 1
     */
    status: CompileStatus;
    /**
     * @generated from protobuf field: repeated Log logs = 2
     */
    logs: Log[];
    /**
     * @generated from protobuf field: repeated Source sources = 3
     */
    sources: Source[];
    /**
     * @generated from protobuf field: string stub = 4
     */
    stub: string;
}
/**
 * @generated from protobuf message Log
 */
export interface Log {
    /**
     * @generated from protobuf field: LogLevel level = 1
     */
    level: LogLevel;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message Source
 */
export interface Source {
    /**
     * @generated from protobuf field: string path = 1
     */
    path: string;
    /**
     * @generated from protobuf field: string content = 2
     */
    content: string;
}
/**
 * @generated from protobuf message GetConfigurationRequest
 */
export interface GetConfigurationRequest {
}
/**
 * @generated from protobuf message WatchConfigurationRequest
 */
export interface WatchConfigurationRequest {
}
/**
 * @generated from protobuf message GetConfigurationResponse
 */
export interface GetConfigurationResponse {
    /**
     * @generated from protobuf field: Configuration configuration = 1
     */
    configuration?: Configuration;
    /**
     * @generated from protobuf field: repeated Log logs = 2
     */
    logs: Log[];
    /**
     * Where each configured variable's value came from, one entry per variable.
     * Neither the file nor the process, but the result of resolving one against
     * the other.
     *
     * @generated from protobuf field: repeated VariableStatus variable_status = 3
     */
    variableStatus: VariableStatus[];
    /**
     * @generated from protobuf field: Runtime runtime = 4
     */
    runtime?: Runtime;
}
/**
 * Runtime is the kaja that is running, as opposed to the workspace it serves.
 * Everything here is settled when the process starts and holds until it exits,
 * and none of it is the user's to set: it is never read from, nor written to,
 * kaja.json, and never accepted as input.
 *
 * @generated from protobuf message Runtime
 */
export interface Runtime {
    /**
     * Whether this kaja may write the workspace it opened - kaja.json and the
     * scripts folder beside it alike. True in the desktop app, which owns its
     * workspace; false in the server, which serves a workspace managed outside
     * kaja - unless it was started with --editable.
     *
     * @generated from protobuf field: bool can_update_configuration = 1
     */
    canUpdateConfiguration: boolean;
    /**
     * Git commit hash or tag for the currently running version
     *
     * @generated from protobuf field: string git_ref = 2
     */
    gitRef: string;
    /**
     * TestFlight/App Store build number (CFBundleVersion), empty for other builds
     *
     * @generated from protobuf field: string build_number = 3
     */
    buildNumber: string;
    /**
     * Whether this machine has somewhere to store a variable's value outside
     * kaja.json (the OS keychain). False on the server, and on a desktop with no
     * usable keyring, where "${secret}" variables can only come from the
     * environment.
     *
     * @generated from protobuf field: bool variable_store_available = 4
     */
    variableStoreAvailable: boolean;
    /**
     * The scripts folder on the machine serving the workspace, for the one thing
     * the UI needs the folder itself for: revealing it in the system file browser.
     *
     * @generated from protobuf field: string scripts_folder = 5
     */
    scriptsFolder: string;
}
/**
 * VariableStatus reports where a variable's value came from. A variable whose
 * value is not written in kaja.json is never sent to the UI, so this is all the
 * Variables tab knows about it.
 *
 * @generated from protobuf message VariableStatus
 */
export interface VariableStatus {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: VariableSource source = 2
     */
    source: VariableSource;
    /**
     * The environment variable consulted for this variable: the name inside
     * ${env:...}, or KAJA_<NAME> for a "${secret}" variable. Empty for a value
     * written in kaja.json.
     *
     * @generated from protobuf field: string env_name = 3
     */
    envName: string;
}
/**
 * SetStoredValue writes a "${secret}" variable's value to the OS keychain. Only
 * the desktop app has one; the web server rejects the call.
 *
 * @generated from protobuf message SetStoredValueRequest
 */
export interface SetStoredValueRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string value = 2
     */
    value: string;
}
/**
 * @generated from protobuf message ClearStoredValueRequest
 */
export interface ClearStoredValueRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
}
/**
 * @generated from protobuf message StoredValueResponse
 */
export interface StoredValueResponse {
    /**
     * @generated from protobuf field: repeated VariableStatus variable_status = 1
     */
    variableStatus: VariableStatus[];
}
/**
 * A script the workspace ships: a .ts file anywhere under the `scripts` folder
 * beside kaja.json. Both builds reach it here - the desktop's window fetches
 * these RPCs over the mux its webview already speaks, a browser fetches them
 * over the wire - which is what puts a script mounted into a container in the
 * sidebar. Writing is the verb a kaja that does not own its workspace refuses,
 * on the one answer `can_update_configuration` reports.
 *
 * @generated from protobuf message Script
 */
export interface Script {
    /**
     * Absolute path on the machine serving the workspace. It identifies the script
     * (the console and the run store are keyed on it) and is not a handle the
     * client may read back: ReadScript takes the name.
     *
     * @generated from protobuf field: string path = 1
     */
    path: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * Only set by ReadScript. A listing carries names, not contents.
     *
     * @generated from protobuf field: string content = 3
     */
    content: string;
    /**
     * The folder the script is filed in, relative to the scripts root and with
     * forward slashes. Empty for one at the root.
     *
     * @generated from protobuf field: string folder = 4
     */
    folder: string;
}
/**
 * @generated from protobuf message ListScriptsRequest
 */
export interface ListScriptsRequest {
}
/**
 * @generated from protobuf message ListScriptsResponse
 */
export interface ListScriptsResponse {
    /**
     * @generated from protobuf field: repeated Script scripts = 1
     */
    scripts: Script[];
}
/**
 * A name is a path within the scripts folder ("reports/churn.ts"), or the
 * absolute path a listing reported, which is the same name said in full. Either
 * way it is never joined onto anything: it is reduced to a relative path and
 * opened through an os.Root over the scripts folder, which is the whole access
 * boundary.
 *
 * @generated from protobuf message ReadScriptRequest
 */
export interface ReadScriptRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
}
/**
 * @generated from protobuf message ReadScriptResponse
 */
export interface ReadScriptResponse {
    /**
     * @generated from protobuf field: Script script = 1
     */
    script?: Script;
}
/**
 * WriteScript writes content back to a script that already exists. Creating one
 * is the other verb.
 *
 * @generated from protobuf message WriteScriptRequest
 */
export interface WriteScriptRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string content = 2
     */
    content: string;
}
/**
 * @generated from protobuf message WriteScriptResponse
 */
export interface WriteScriptResponse {
    /**
     * @generated from protobuf field: Script script = 1
     */
    script?: Script;
}
/**
 * CreateScript writes a new script. The name may name a folder, which is created
 * if it isn't there, and a `.ts` extension is added if the name doesn't carry
 * one - naming a draft asks for a name, not for a filename.
 *
 * @generated from protobuf message CreateScriptRequest
 */
export interface CreateScriptRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string content = 2
     */
    content: string;
}
/**
 * @generated from protobuf message CreateScriptResponse
 */
export interface CreateScriptResponse {
    /**
     * @generated from protobuf field: Script script = 1
     */
    script?: Script;
}
/**
 * RenameScript renames a script and, when the new name carries a folder, moves
 * it there. Renaming and moving are one operation because on disk they are one:
 * the file's path is its name.
 *
 * @generated from protobuf message RenameScriptRequest
 */
export interface RenameScriptRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string new_name = 2
     */
    newName: string;
}
/**
 * @generated from protobuf message RenameScriptResponse
 */
export interface RenameScriptResponse {
    /**
     * @generated from protobuf field: Script script = 1
     */
    script?: Script;
}
/**
 * @generated from protobuf message DeleteScriptRequest
 */
export interface DeleteScriptRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
}
/**
 * @generated from protobuf message DeleteScriptResponse
 */
export interface DeleteScriptResponse {
}
/**
 * ListScriptFolders returns every directory under the scripts root, relative and
 * slash-separated. An empty one is in the list: it is a directory, not a UI
 * grouping, so it has no file to be inferred from.
 *
 * @generated from protobuf message ListScriptFoldersRequest
 */
export interface ListScriptFoldersRequest {
}
/**
 * @generated from protobuf message ListScriptFoldersResponse
 */
export interface ListScriptFoldersResponse {
    /**
     * @generated from protobuf field: repeated string folders = 1
     */
    folders: string[];
}
/**
 * @generated from protobuf message CreateScriptFolderRequest
 */
export interface CreateScriptFolderRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
}
/**
 * @generated from protobuf message CreateScriptFolderResponse
 */
export interface CreateScriptFolderResponse {
    /**
     * @generated from protobuf field: string folder = 1
     */
    folder: string;
}
/**
 * RenameScriptFolder takes a folder name, not a path: a folder is renamed where
 * it is, and moving one is not offered.
 *
 * @generated from protobuf message RenameScriptFolderRequest
 */
export interface RenameScriptFolderRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string new_name = 2
     */
    newName: string;
}
/**
 * @generated from protobuf message RenameScriptFolderResponse
 */
export interface RenameScriptFolderResponse {
    /**
     * @generated from protobuf field: string folder = 1
     */
    folder: string;
}
/**
 * DeleteScriptFolder removes a folder and everything filed there. What that costs
 * is named in the confirmation rather than refused here, and a folder that is
 * already gone is not a failure - the act asked for is done.
 *
 * @generated from protobuf message DeleteScriptFolderRequest
 */
export interface DeleteScriptFolderRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
}
/**
 * @generated from protobuf message DeleteScriptFolderResponse
 */
export interface DeleteScriptFolderResponse {
}
/**
 * ScanScriptVariables reports which scripts reference the named variables. An
 * app's references are read out of the configuration the client already holds;
 * a script's cost a read of the file, so they are answered here, in one walk of
 * the scripts folder, rather than a search per variable the client has to pace.
 *
 * A script names a variable two ways, and both are counted: `kaja.variables.NAME`,
 * which is how a script reads one, and `${NAME}` inside a value it sends, which
 * the request hop expands. The names come from the caller, so an interpolated
 * local can only be counted if it is spelled exactly like a variable.
 *
 * @generated from protobuf message ScanScriptVariablesRequest
 */
export interface ScanScriptVariablesRequest {
    /**
     * @generated from protobuf field: repeated string names = 1
     */
    names: string[];
}
/**
 * One script that references a variable, and how many times.
 *
 * @generated from protobuf message ScriptReference
 */
export interface ScriptReference {
    /**
     * Absolute path, as ListScripts reports it.
     *
     * @generated from protobuf field: string path = 1
     */
    path: string;
    /**
     * @generated from protobuf field: int32 count = 2
     */
    count: number;
}
/**
 * @generated from protobuf message VariableReferences
 */
export interface VariableReferences {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: repeated ScriptReference scripts = 2
     */
    scripts: ScriptReference[];
}
/**
 * @generated from protobuf message ScanScriptVariablesResponse
 */
export interface ScanScriptVariablesResponse {
    /**
     * One entry per requested name, whether or not anything references it.
     *
     * @generated from protobuf field: repeated VariableReferences variables = 1
     */
    variables: VariableReferences[];
    /**
     * Set when the walk stopped short of the whole folder, so the counts read as a
     * floor rather than a total.
     *
     * @generated from protobuf field: bool truncated = 2
     */
    truncated: boolean;
}
/**
 * @generated from protobuf message Configuration
 */
export interface Configuration {
    /**
     * kaja can be deployed at a subpath - i.e. kaja.tools/demo
     * This field is used to set the subpath.
     * The server uses it to generate the correct paths in HTML and redirects.
     * The JS code is using relative paths and should be not dependent on this.
     *
     * @generated from protobuf field: string path_prefix = 1
     */
    pathPrefix: string;
    /**
     * Apps are the single unit of configuration. A gRPC or Twirp service is just an
     * app of type "grpc"/"twirp"; built-in integrations like "openapi" or "folder"
     * are apps too. kaja renders and invokes every app the same way.
     *
     * @generated from protobuf field: repeated ConfigurationApp apps = 5
     */
    apps: ConfigurationApp[];
    /**
     * User-defined variables, referenced as `${NAME}` in app configuration and read
     * from scripts as `kaja.variables.<name>`. A value is either literal, or names
     * the source that holds it outside this file: "${secret}" (the OS keychain, or
     * KAJA_<NAME> in the environment) or "${env:X}" (the environment variable X,
     * which may sit inside a longer value). Only literal values are ever sent to a
     * remote browser.
     *
     * @generated from protobuf field: map<string, string> variables = 6
     */
    variables: {
        [key: string]: string;
    };
}
/**
 * ConfigurationApp is one app: a name and exactly one typed block whose key is the
 * app's type. The block declares the parameters that type needs (so two types can
 * never be mixed in one app); the server flattens its scalar fields to a string map
 * for the app contract.
 *
 * @generated from protobuf message ConfigurationApp
 */
export interface ConfigurationApp {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf oneof: app
     */
    app: {
        oneofKind: "grpc";
        /**
         * @generated from protobuf field: GrpcApp grpc = 2
         */
        grpc: GrpcApp;
    } | {
        oneofKind: "twirp";
        /**
         * @generated from protobuf field: TwirpApp twirp = 3
         */
        twirp: TwirpApp;
    } | {
        oneofKind: "openapi";
        /**
         * @generated from protobuf field: OpenApiApp openapi = 4
         */
        openapi: OpenApiApp;
    } | {
        oneofKind: "openai";
        /**
         * @generated from protobuf field: OpenAiApp openai = 5
         */
        openai: OpenAiApp;
    } | {
        oneofKind: "folder";
        /**
         * @generated from protobuf field: FolderApp folder = 7
         */
        folder: FolderApp;
    } | {
        oneofKind: "mcp";
        /**
         * @generated from protobuf field: McpApp mcp = 8
         */
        mcp: McpApp;
    } | {
        oneofKind: undefined;
    };
}
/**
 * GrpcApp calls a gRPC service. Its proto surface comes from a workspace-relative
 * proto_dir, or from server reflection when reflection is set. headers are
 * forwarded (as metadata) with each request.
 *
 * The credential and the transport are the app's, not the request's: kaja
 * resolves them where it holds them and applies them as it makes the call, so a
 * "${secret}" token is never handed to the browser and Basic's base64 is never
 * something to work out by hand.
 *
 * @generated from protobuf message GrpcApp
 */
export interface GrpcApp {
    /**
     * @generated from protobuf field: string url = 1
     */
    url: string;
    /**
     * @generated from protobuf field: string proto_dir = 2
     */
    protoDir: string;
    /**
     * @generated from protobuf field: bool reflection = 3
     */
    reflection: boolean;
    /**
     * @generated from protobuf field: map<string, string> headers = 4
     */
    headers: {
        [key: string]: string;
    };
    /**
     * Whether to speak TLS: "on", "off", or empty to let the URL decide (an
     * https/grpcs scheme, or port 443).
     *
     * @generated from protobuf field: string tls = 5
     */
    tls: string;
    /**
     * Accept whatever certificate the server presents. For a development server
     * with a self-signed certificate, and nothing else.
     *
     * @generated from protobuf field: bool insecure_skip_verify = 6
     */
    insecureSkipVerify: boolean;
    /**
     * PEM bundle the server's certificate is verified against, instead of the
     * system roots. Workspace-relative, like proto_dir.
     *
     * @generated from protobuf field: string ca_file = 7
     */
    caFile: string;
    /**
     * Client certificate and key kaja presents to the server (mutual TLS).
     * Workspace-relative, like proto_dir.
     *
     * @generated from protobuf field: string client_cert_file = 8
     */
    clientCertFile: string;
    /**
     * @generated from protobuf field: string client_key_file = 9
     */
    clientKeyFile: string;
    /**
     * The credential sent with every call: "bearer", "basic", "apikey", or
     * "none". Empty means none.
     *
     * @generated from protobuf field: string auth = 10
     */
    auth: string;
    /**
     * The bearer token, or the key for the "apikey" credential.
     *
     * @generated from protobuf field: string token = 11
     */
    token: string;
    /**
     * @generated from protobuf field: string username = 12
     */
    username: string;
    /**
     * @generated from protobuf field: string password = 13
     */
    password: string;
    /**
     * Metadata key the "apikey" credential is sent under. Empty means
     * "x-api-key".
     *
     * @generated from protobuf field: string api_key_name = 14
     */
    apiKeyName: string;
}
/**
 * TwirpApp calls a Twirp service described by a workspace-relative proto_dir.
 *
 * @generated from protobuf message TwirpApp
 */
export interface TwirpApp {
    /**
     * @generated from protobuf field: string url = 1
     */
    url: string;
    /**
     * @generated from protobuf field: string proto_dir = 2
     */
    protoDir: string;
    /**
     * @generated from protobuf field: map<string, string> headers = 3
     */
    headers: {
        [key: string]: string;
    };
}
/**
 * OpenApiApp calls a REST API from its OpenAPI 3.x document. The document is
 * taken from spec_url or, when the spec is uploaded, from spec_content (raw JSON
 * or YAML). Credentials are applied per the spec's security schemes. base_url
 * overrides the upstream base URL derived from the spec's servers list.
 *
 * @generated from protobuf message OpenApiApp
 */
export interface OpenApiApp {
    /**
     * @generated from protobuf field: string spec_url = 1
     */
    specUrl: string;
    /**
     * @generated from protobuf field: string token = 2
     */
    token: string;
    /**
     * @generated from protobuf field: string username = 3
     */
    username: string;
    /**
     * @generated from protobuf field: string password = 4
     */
    password: string;
    /**
     * @generated from protobuf field: map<string, string> headers = 5
     */
    headers: {
        [key: string]: string;
    };
    /**
     * @generated from protobuf field: string spec_content = 6
     */
    specContent: string;
    /**
     * @generated from protobuf field: string base_url = 7
     */
    baseUrl: string;
    /**
     * Which of the document's security schemes the credentials belong to, by its
     * name in components.securitySchemes. Empty picks a scheme from the document;
     * "none" sends no credentials at all.
     *
     * @generated from protobuf field: string security_scheme = 8
     */
    securityScheme: string;
    /**
     * A single header sent while fetching spec_url, for documents that are
     * themselves behind a login. Kept apart from the credentials above because the
     * document and the API it describes often want different tokens.
     *
     * @generated from protobuf field: string spec_header_name = 9
     */
    specHeaderName: string;
    /**
     * @generated from protobuf field: string spec_header_value = 10
     */
    specHeaderValue: string;
}
/**
 * OpenAiApp calls a chat model over one of two APIs: OpenAI chat completions, or
 * the Claude Messages API. `api` says which, because the two differ in the body
 * and the response as much as in the credential's header, and an endpoint behind a
 * gateway doesn't say either.
 *
 * The credential is the app's, not the request's: kaja resolves it where it holds
 * it and applies it on the way out, so a "${secret}" token is never handed to the
 * browser.
 *
 * @generated from protobuf message OpenAiApp
 */
export interface OpenAiApp {
    /**
     * @generated from protobuf field: string endpoint = 1
     */
    endpoint: string;
    /**
     * @generated from protobuf field: string token = 2
     */
    token: string;
    /**
     * @generated from protobuf field: map<string, string> headers = 3
     */
    headers: {
        [key: string]: string;
    };
    /**
     * The API the endpoint speaks: "openai" or "anthropic". Empty means "openai".
     *
     * @generated from protobuf field: string api = 4
     */
    api: string;
    /**
     * The credential sent with every request: "bearer", "apikey", or "none". Empty
     * means whichever one the API's own dashboard hands you - a bearer token for
     * OpenAI, a key under x-api-key for Claude.
     *
     * @generated from protobuf field: string auth = 5
     */
    auth: string;
    /**
     * Header the "apikey" credential is sent under. Empty means "x-api-key".
     *
     * @generated from protobuf field: string api_key_name = 6
     */
    apiKeyName: string;
}
/**
 * FolderApp lists, creates, reads and appends to files in a folder on disk. It
 * is local, so it forwards no headers.
 *
 * @generated from protobuf message FolderApp
 */
export interface FolderApp {
    /**
     * @generated from protobuf field: string path = 1
     */
    path: string;
}
/**
 * McpApp explores another Model Context Protocol server over the Streamable HTTP
 * transport. Its proto surface is generated from what that server exposes: one
 * method per tool, one per prompt, and the list/read methods for its resources.
 *
 * The credential is the app's, not the request's: kaja resolves it where it
 * holds it and applies it on the way out, so a "${secret}" token is never handed
 * to the browser.
 *
 * @generated from protobuf message McpApp
 */
export interface McpApp {
    /**
     * The server's MCP endpoint, e.g. "https://example.com/mcp".
     *
     * @generated from protobuf field: string url = 1
     */
    url: string;
    /**
     * @generated from protobuf field: map<string, string> headers = 2
     */
    headers: {
        [key: string]: string;
    };
    /**
     * The credential sent with every request: "bearer", "apikey", or "none". Empty
     * means bearer, which is what an MCP server behind a login nearly always
     * wants.
     *
     * @generated from protobuf field: string auth = 3
     */
    auth: string;
    /**
     * The bearer token, or the key for the "apikey" credential.
     *
     * @generated from protobuf field: string token = 4
     */
    token: string;
    /**
     * Header the "apikey" credential is sent under. Empty means "X-API-Key".
     *
     * @generated from protobuf field: string api_key_name = 5
     */
    apiKeyName: string;
}
/**
 * @generated from protobuf message UpdateConfigurationRequest
 */
export interface UpdateConfigurationRequest {
    /**
     * @generated from protobuf field: Configuration configuration = 1
     */
    configuration?: Configuration;
}
/**
 * @generated from protobuf message UpdateConfigurationResponse
 */
export interface UpdateConfigurationResponse {
    /**
     * @generated from protobuf field: Configuration configuration = 1
     */
    configuration?: Configuration;
    /**
     * Where each variable's value came from, re-resolved against what was saved.
     *
     * @generated from protobuf field: repeated VariableStatus variable_status = 2
     */
    variableStatus: VariableStatus[];
}
/**
 * @generated from protobuf enum OpenStatus
 */
export enum OpenStatus {
    /**
     * @generated from protobuf enum value: OPEN_STATUS_UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: OPEN_STATUS_OK = 1;
     */
    OK = 1,
    /**
     * @generated from protobuf enum value: OPEN_STATUS_ERROR = 2;
     */
    ERROR = 2
}
/**
 * @generated from protobuf enum GrpcProblemKind
 */
export enum GrpcProblemKind {
    /**
     * @generated from protobuf enum value: GRPC_PROBLEM_UNKNOWN = 0;
     */
    GRPC_PROBLEM_UNKNOWN = 0,
    /**
     * The host couldn't be reached (DNS, TCP).
     *
     * @generated from protobuf enum value: GRPC_PROBLEM_UNREACHABLE = 1;
     */
    GRPC_PROBLEM_UNREACHABLE = 1,
    /**
     * The TLS handshake failed, which usually means the transport is set the
     * wrong way round or the certificate isn't trusted.
     *
     * @generated from protobuf enum value: GRPC_PROBLEM_TLS = 2;
     */
    GRPC_PROBLEM_TLS = 2,
    /**
     * The server answered but doesn't serve the reflection API.
     *
     * @generated from protobuf enum value: GRPC_PROBLEM_NO_REFLECTION = 3;
     */
    GRPC_PROBLEM_NO_REFLECTION = 3,
    /**
     * Reflection is there but wants credentials.
     *
     * @generated from protobuf enum value: GRPC_PROBLEM_UNAUTHENTICATED = 4;
     */
    GRPC_PROBLEM_UNAUTHENTICATED = 4,
    /**
     * Credentials were sent and rejected.
     *
     * @generated from protobuf enum value: GRPC_PROBLEM_PERMISSION_DENIED = 5;
     */
    GRPC_PROBLEM_PERMISSION_DENIED = 5,
    /**
     * Reflection answered with nothing but its own service.
     *
     * @generated from protobuf enum value: GRPC_PROBLEM_NO_SERVICES = 6;
     */
    GRPC_PROBLEM_NO_SERVICES = 6,
    /**
     * @generated from protobuf enum value: GRPC_PROBLEM_TIMEOUT = 7;
     */
    GRPC_PROBLEM_TIMEOUT = 7,
    /**
     * The proto directory holds no .proto files, or doesn't exist.
     *
     * @generated from protobuf enum value: GRPC_PROBLEM_NO_PROTO_FILES = 8;
     */
    GRPC_PROBLEM_NO_PROTO_FILES = 8,
    /**
     * The proto files are there but don't compile.
     *
     * @generated from protobuf enum value: GRPC_PROBLEM_PROTO_INVALID = 9;
     */
    GRPC_PROBLEM_PROTO_INVALID = 9,
    /**
     * The URL isn't a usable gRPC target.
     *
     * @generated from protobuf enum value: GRPC_PROBLEM_TARGET = 10;
     */
    GRPC_PROBLEM_TARGET = 10
}
/**
 * @generated from protobuf enum OpenApiProblemKind
 */
export enum OpenApiProblemKind {
    /**
     * @generated from protobuf enum value: OPEN_API_PROBLEM_UNKNOWN = 0;
     */
    OPEN_API_PROBLEM_UNKNOWN = 0,
    /**
     * The host couldn't be reached (DNS, TCP, TLS).
     *
     * @generated from protobuf enum value: OPEN_API_PROBLEM_UNREACHABLE = 1;
     */
    OPEN_API_PROBLEM_UNREACHABLE = 1,
    /**
     * The document itself is behind a login (401/403).
     *
     * @generated from protobuf enum value: OPEN_API_PROBLEM_UNAUTHORIZED = 2;
     */
    OPEN_API_PROBLEM_UNAUTHORIZED = 2,
    /**
     * Any other non-200 response.
     *
     * @generated from protobuf enum value: OPEN_API_PROBLEM_HTTP_ERROR = 3;
     */
    OPEN_API_PROBLEM_HTTP_ERROR = 3,
    /**
     * The response is an HTML page, almost always a login redirect or docs page.
     *
     * @generated from protobuf enum value: OPEN_API_PROBLEM_HTML = 4;
     */
    OPEN_API_PROBLEM_HTML = 4,
    /**
     * Parsed, but it isn't an OpenAPI document.
     *
     * @generated from protobuf enum value: OPEN_API_PROBLEM_NOT_A_DOCUMENT = 5;
     */
    OPEN_API_PROBLEM_NOT_A_DOCUMENT = 5,
    /**
     * A Swagger 2.0 document, which kaja doesn't read.
     *
     * @generated from protobuf enum value: OPEN_API_PROBLEM_SWAGGER2 = 6;
     */
    OPEN_API_PROBLEM_SWAGGER2 = 6,
    /**
     * Not parseable as JSON or YAML.
     *
     * @generated from protobuf enum value: OPEN_API_PROBLEM_MALFORMED = 7;
     */
    OPEN_API_PROBLEM_MALFORMED = 7
}
/**
 * @generated from protobuf enum McpProblemKind
 */
export enum McpProblemKind {
    /**
     * @generated from protobuf enum value: MCP_PROBLEM_UNKNOWN = 0;
     */
    MCP_PROBLEM_UNKNOWN = 0,
    /**
     * The URL isn't a usable HTTP endpoint.
     *
     * @generated from protobuf enum value: MCP_PROBLEM_TARGET = 1;
     */
    MCP_PROBLEM_TARGET = 1,
    /**
     * The host couldn't be reached (DNS, TCP, TLS).
     *
     * @generated from protobuf enum value: MCP_PROBLEM_UNREACHABLE = 2;
     */
    MCP_PROBLEM_UNREACHABLE = 2,
    /**
     * @generated from protobuf enum value: MCP_PROBLEM_TIMEOUT = 3;
     */
    MCP_PROBLEM_TIMEOUT = 3,
    /**
     * The server wants a credential.
     *
     * @generated from protobuf enum value: MCP_PROBLEM_UNAUTHORIZED = 4;
     */
    MCP_PROBLEM_UNAUTHORIZED = 4,
    /**
     * A credential was sent and rejected.
     *
     * @generated from protobuf enum value: MCP_PROBLEM_FORBIDDEN = 5;
     */
    MCP_PROBLEM_FORBIDDEN = 5,
    /**
     * Any other non-200 response.
     *
     * @generated from protobuf enum value: MCP_PROBLEM_HTTP_ERROR = 6;
     */
    MCP_PROBLEM_HTTP_ERROR = 6,
    /**
     * Something answered, but it doesn't speak MCP.
     *
     * @generated from protobuf enum value: MCP_PROBLEM_NOT_MCP = 7;
     */
    MCP_PROBLEM_NOT_MCP = 7,
    /**
     * It speaks MCP and exposes nothing.
     *
     * @generated from protobuf enum value: MCP_PROBLEM_EMPTY = 8;
     */
    MCP_PROBLEM_EMPTY = 8
}
/**
 * @generated from protobuf enum CompileStatus
 */
export enum CompileStatus {
    /**
     * @generated from protobuf enum value: STATUS_UNKNOWN = 0;
     */
    STATUS_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: STATUS_READY = 1;
     */
    STATUS_READY = 1,
    /**
     * @generated from protobuf enum value: STATUS_ERROR = 2;
     */
    STATUS_ERROR = 2,
    /**
     * @generated from protobuf enum value: STATUS_RUNNING = 3;
     */
    STATUS_RUNNING = 3
}
/**
 * @generated from protobuf enum LogLevel
 */
export enum LogLevel {
    /**
     * @generated from protobuf enum value: LEVEL_DEBUG = 0;
     */
    LEVEL_DEBUG = 0,
    /**
     * @generated from protobuf enum value: LEVEL_INFO = 1;
     */
    LEVEL_INFO = 1,
    /**
     * @generated from protobuf enum value: LEVEL_WARN = 2;
     */
    LEVEL_WARN = 2,
    /**
     * @generated from protobuf enum value: LEVEL_ERROR = 3;
     */
    LEVEL_ERROR = 3
}
/**
 * @generated from protobuf enum VariableSource
 */
export enum VariableSource {
    /**
     * The variable names a source, but the source holds nothing on this machine.
     *
     * @generated from protobuf enum value: VARIABLE_SOURCE_UNSET = 0;
     */
    UNSET = 0,
    /**
     * The value is written in kaja.json.
     *
     * @generated from protobuf enum value: VARIABLE_SOURCE_FILE = 1;
     */
    FILE = 1,
    /**
     * The value came from the OS keychain.
     *
     * @generated from protobuf enum value: VARIABLE_SOURCE_KEYCHAIN = 2;
     */
    KEYCHAIN = 2,
    /**
     * The value came from an environment variable.
     *
     * @generated from protobuf enum value: VARIABLE_SOURCE_ENVIRONMENT = 3;
     */
    ENVIRONMENT = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class CompileRequest$Type extends MessageType<CompileRequest> {
    constructor() {
        super("CompileRequest", [
            { no: 1, name: "proto_dir", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CompileRequest
 */
export const CompileRequest = new CompileRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OpenAppRequest$Type extends MessageType<OpenAppRequest> {
    constructor() {
        super("OpenAppRequest", [
            { no: 1, name: "app", kind: "message", T: () => ConfigurationApp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message OpenAppRequest
 */
export const OpenAppRequest = new OpenAppRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OpenAppResponse$Type extends MessageType<OpenAppResponse> {
    constructor() {
        super("OpenAppResponse", [
            { no: 1, name: "status", kind: "enum", T: () => ["OpenStatus", OpenStatus, "OPEN_STATUS_"] },
            { no: 2, name: "logs", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Log },
            { no: 3, name: "proto_dir", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message OpenAppResponse
 */
export const OpenAppResponse = new OpenAppResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InspectGrpcRequest$Type extends MessageType<InspectGrpcRequest> {
    constructor() {
        super("InspectGrpcRequest", [
            { no: 1, name: "grpc", kind: "message", T: () => GrpcApp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message InspectGrpcRequest
 */
export const InspectGrpcRequest = new InspectGrpcRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InspectGrpcResponse$Type extends MessageType<InspectGrpcResponse> {
    constructor() {
        super("InspectGrpcResponse", [
            { no: 1, name: "server", kind: "message", T: () => GrpcServer },
            { no: 2, name: "problem", kind: "message", T: () => GrpcProblem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message InspectGrpcResponse
 */
export const InspectGrpcResponse = new InspectGrpcResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GrpcServer$Type extends MessageType<GrpcServer> {
    constructor() {
        super("GrpcServer", [
            { no: 1, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "target", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "tls", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "services", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => GrpcService },
            { no: 5, name: "method_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "reflection_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "file_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "proto_dir", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "reachable", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message GrpcServer
 */
export const GrpcServer = new GrpcServer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GrpcService$Type extends MessageType<GrpcService> {
    constructor() {
        super("GrpcService", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "method_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "client_streaming_method_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message GrpcService
 */
export const GrpcService = new GrpcService$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GrpcProblem$Type extends MessageType<GrpcProblem> {
    constructor() {
        super("GrpcProblem", [
            { no: 1, name: "kind", kind: "enum", T: () => ["GrpcProblemKind", GrpcProblemKind] },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "detail", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message GrpcProblem
 */
export const GrpcProblem = new GrpcProblem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InspectOpenApiRequest$Type extends MessageType<InspectOpenApiRequest> {
    constructor() {
        super("InspectOpenApiRequest", [
            { no: 1, name: "openapi", kind: "message", T: () => OpenApiApp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message InspectOpenApiRequest
 */
export const InspectOpenApiRequest = new InspectOpenApiRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InspectOpenApiResponse$Type extends MessageType<InspectOpenApiResponse> {
    constructor() {
        super("InspectOpenApiResponse", [
            { no: 1, name: "document", kind: "message", T: () => OpenApiDocument },
            { no: 2, name: "problem", kind: "message", T: () => OpenApiProblem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message InspectOpenApiResponse
 */
export const InspectOpenApiResponse = new InspectOpenApiResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OpenApiDocument$Type extends MessageType<OpenApiDocument> {
    constructor() {
        super("OpenApiDocument", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "openapi_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "operation_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "tag_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "servers", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => OpenApiServer },
            { no: 7, name: "security_schemes", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => OpenApiSecurityScheme },
            { no: 8, name: "guessed_base_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "per_operation_security", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message OpenApiDocument
 */
export const OpenApiDocument = new OpenApiDocument$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OpenApiServer$Type extends MessageType<OpenApiServer> {
    constructor() {
        super("OpenApiServer", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "variables", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => OpenApiServerVariable }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message OpenApiServer
 */
export const OpenApiServer = new OpenApiServer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OpenApiServerVariable$Type extends MessageType<OpenApiServerVariable> {
    constructor() {
        super("OpenApiServerVariable", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "default_value", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "enum_values", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message OpenApiServerVariable
 */
export const OpenApiServerVariable = new OpenApiServerVariable$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OpenApiSecurityScheme$Type extends MessageType<OpenApiSecurityScheme> {
    constructor() {
        super("OpenApiSecurityScheme", [
            { no: 1, name: "key", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "scheme", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "bearer_format", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "in", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "parameter_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "open_id_connect_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "operation_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "requires_others", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message OpenApiSecurityScheme
 */
export const OpenApiSecurityScheme = new OpenApiSecurityScheme$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OpenApiProblem$Type extends MessageType<OpenApiProblem> {
    constructor() {
        super("OpenApiProblem", [
            { no: 1, name: "kind", kind: "enum", T: () => ["OpenApiProblemKind", OpenApiProblemKind] },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "detail", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message OpenApiProblem
 */
export const OpenApiProblem = new OpenApiProblem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InspectMcpRequest$Type extends MessageType<InspectMcpRequest> {
    constructor() {
        super("InspectMcpRequest", [
            { no: 1, name: "mcp", kind: "message", T: () => McpApp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message InspectMcpRequest
 */
export const InspectMcpRequest = new InspectMcpRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InspectMcpResponse$Type extends MessageType<InspectMcpResponse> {
    constructor() {
        super("InspectMcpResponse", [
            { no: 1, name: "server", kind: "message", T: () => McpServer },
            { no: 2, name: "problem", kind: "message", T: () => McpProblem }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message InspectMcpResponse
 */
export const InspectMcpResponse = new InspectMcpResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class McpServer$Type extends MessageType<McpServer> {
    constructor() {
        super("McpServer", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "protocol_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "handshake", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "supported_versions", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "tool_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "resource_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "resource_template_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "prompt_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "tools", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => McpTool },
            { no: 11, name: "instructions", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message McpServer
 */
export const McpServer = new McpServer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class McpTool$Type extends MessageType<McpTool> {
    constructor() {
        super("McpTool", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "read_only", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message McpTool
 */
export const McpTool = new McpTool$Type();
// @generated message type with reflection information, may provide speed optimized methods
class McpProblem$Type extends MessageType<McpProblem> {
    constructor() {
        super("McpProblem", [
            { no: 1, name: "kind", kind: "enum", T: () => ["McpProblemKind", McpProblemKind] },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "detail", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message McpProblem
 */
export const McpProblem = new McpProblem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CompileResponse$Type extends MessageType<CompileResponse> {
    constructor() {
        super("CompileResponse", [
            { no: 1, name: "status", kind: "enum", T: () => ["CompileStatus", CompileStatus] },
            { no: 2, name: "logs", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Log },
            { no: 3, name: "sources", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Source },
            { no: 4, name: "stub", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CompileResponse
 */
export const CompileResponse = new CompileResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Log$Type extends MessageType<Log> {
    constructor() {
        super("Log", [
            { no: 1, name: "level", kind: "enum", T: () => ["LogLevel", LogLevel] },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Log
 */
export const Log = new Log$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Source$Type extends MessageType<Source> {
    constructor() {
        super("Source", [
            { no: 1, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Source
 */
export const Source = new Source$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetConfigurationRequest$Type extends MessageType<GetConfigurationRequest> {
    constructor() {
        super("GetConfigurationRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message GetConfigurationRequest
 */
export const GetConfigurationRequest = new GetConfigurationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WatchConfigurationRequest$Type extends MessageType<WatchConfigurationRequest> {
    constructor() {
        super("WatchConfigurationRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message WatchConfigurationRequest
 */
export const WatchConfigurationRequest = new WatchConfigurationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetConfigurationResponse$Type extends MessageType<GetConfigurationResponse> {
    constructor() {
        super("GetConfigurationResponse", [
            { no: 1, name: "configuration", kind: "message", T: () => Configuration },
            { no: 2, name: "logs", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Log },
            { no: 3, name: "variable_status", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => VariableStatus },
            { no: 4, name: "runtime", kind: "message", T: () => Runtime }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message GetConfigurationResponse
 */
export const GetConfigurationResponse = new GetConfigurationResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Runtime$Type extends MessageType<Runtime> {
    constructor() {
        super("Runtime", [
            { no: 1, name: "can_update_configuration", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "git_ref", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "build_number", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "variable_store_available", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "scripts_folder", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Runtime
 */
export const Runtime = new Runtime$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VariableStatus$Type extends MessageType<VariableStatus> {
    constructor() {
        super("VariableStatus", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "source", kind: "enum", T: () => ["VariableSource", VariableSource, "VARIABLE_SOURCE_"] },
            { no: 3, name: "env_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message VariableStatus
 */
export const VariableStatus = new VariableStatus$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetStoredValueRequest$Type extends MessageType<SetStoredValueRequest> {
    constructor() {
        super("SetStoredValueRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "value", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message SetStoredValueRequest
 */
export const SetStoredValueRequest = new SetStoredValueRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClearStoredValueRequest$Type extends MessageType<ClearStoredValueRequest> {
    constructor() {
        super("ClearStoredValueRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ClearStoredValueRequest
 */
export const ClearStoredValueRequest = new ClearStoredValueRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StoredValueResponse$Type extends MessageType<StoredValueResponse> {
    constructor() {
        super("StoredValueResponse", [
            { no: 1, name: "variable_status", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => VariableStatus }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message StoredValueResponse
 */
export const StoredValueResponse = new StoredValueResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Script$Type extends MessageType<Script> {
    constructor() {
        super("Script", [
            { no: 1, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "folder", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Script
 */
export const Script = new Script$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListScriptsRequest$Type extends MessageType<ListScriptsRequest> {
    constructor() {
        super("ListScriptsRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message ListScriptsRequest
 */
export const ListScriptsRequest = new ListScriptsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListScriptsResponse$Type extends MessageType<ListScriptsResponse> {
    constructor() {
        super("ListScriptsResponse", [
            { no: 1, name: "scripts", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Script }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ListScriptsResponse
 */
export const ListScriptsResponse = new ListScriptsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadScriptRequest$Type extends MessageType<ReadScriptRequest> {
    constructor() {
        super("ReadScriptRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ReadScriptRequest
 */
export const ReadScriptRequest = new ReadScriptRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadScriptResponse$Type extends MessageType<ReadScriptResponse> {
    constructor() {
        super("ReadScriptResponse", [
            { no: 1, name: "script", kind: "message", T: () => Script }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ReadScriptResponse
 */
export const ReadScriptResponse = new ReadScriptResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WriteScriptRequest$Type extends MessageType<WriteScriptRequest> {
    constructor() {
        super("WriteScriptRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message WriteScriptRequest
 */
export const WriteScriptRequest = new WriteScriptRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WriteScriptResponse$Type extends MessageType<WriteScriptResponse> {
    constructor() {
        super("WriteScriptResponse", [
            { no: 1, name: "script", kind: "message", T: () => Script }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message WriteScriptResponse
 */
export const WriteScriptResponse = new WriteScriptResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateScriptRequest$Type extends MessageType<CreateScriptRequest> {
    constructor() {
        super("CreateScriptRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CreateScriptRequest
 */
export const CreateScriptRequest = new CreateScriptRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateScriptResponse$Type extends MessageType<CreateScriptResponse> {
    constructor() {
        super("CreateScriptResponse", [
            { no: 1, name: "script", kind: "message", T: () => Script }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CreateScriptResponse
 */
export const CreateScriptResponse = new CreateScriptResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RenameScriptRequest$Type extends MessageType<RenameScriptRequest> {
    constructor() {
        super("RenameScriptRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "new_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message RenameScriptRequest
 */
export const RenameScriptRequest = new RenameScriptRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RenameScriptResponse$Type extends MessageType<RenameScriptResponse> {
    constructor() {
        super("RenameScriptResponse", [
            { no: 1, name: "script", kind: "message", T: () => Script }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message RenameScriptResponse
 */
export const RenameScriptResponse = new RenameScriptResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteScriptRequest$Type extends MessageType<DeleteScriptRequest> {
    constructor() {
        super("DeleteScriptRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message DeleteScriptRequest
 */
export const DeleteScriptRequest = new DeleteScriptRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteScriptResponse$Type extends MessageType<DeleteScriptResponse> {
    constructor() {
        super("DeleteScriptResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message DeleteScriptResponse
 */
export const DeleteScriptResponse = new DeleteScriptResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListScriptFoldersRequest$Type extends MessageType<ListScriptFoldersRequest> {
    constructor() {
        super("ListScriptFoldersRequest", []);
    }
}
/**
 * @generated MessageType for protobuf message ListScriptFoldersRequest
 */
export const ListScriptFoldersRequest = new ListScriptFoldersRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListScriptFoldersResponse$Type extends MessageType<ListScriptFoldersResponse> {
    constructor() {
        super("ListScriptFoldersResponse", [
            { no: 1, name: "folders", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ListScriptFoldersResponse
 */
export const ListScriptFoldersResponse = new ListScriptFoldersResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateScriptFolderRequest$Type extends MessageType<CreateScriptFolderRequest> {
    constructor() {
        super("CreateScriptFolderRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CreateScriptFolderRequest
 */
export const CreateScriptFolderRequest = new CreateScriptFolderRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateScriptFolderResponse$Type extends MessageType<CreateScriptFolderResponse> {
    constructor() {
        super("CreateScriptFolderResponse", [
            { no: 1, name: "folder", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CreateScriptFolderResponse
 */
export const CreateScriptFolderResponse = new CreateScriptFolderResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RenameScriptFolderRequest$Type extends MessageType<RenameScriptFolderRequest> {
    constructor() {
        super("RenameScriptFolderRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "new_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message RenameScriptFolderRequest
 */
export const RenameScriptFolderRequest = new RenameScriptFolderRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RenameScriptFolderResponse$Type extends MessageType<RenameScriptFolderResponse> {
    constructor() {
        super("RenameScriptFolderResponse", [
            { no: 1, name: "folder", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message RenameScriptFolderResponse
 */
export const RenameScriptFolderResponse = new RenameScriptFolderResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteScriptFolderRequest$Type extends MessageType<DeleteScriptFolderRequest> {
    constructor() {
        super("DeleteScriptFolderRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message DeleteScriptFolderRequest
 */
export const DeleteScriptFolderRequest = new DeleteScriptFolderRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteScriptFolderResponse$Type extends MessageType<DeleteScriptFolderResponse> {
    constructor() {
        super("DeleteScriptFolderResponse", []);
    }
}
/**
 * @generated MessageType for protobuf message DeleteScriptFolderResponse
 */
export const DeleteScriptFolderResponse = new DeleteScriptFolderResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScanScriptVariablesRequest$Type extends MessageType<ScanScriptVariablesRequest> {
    constructor() {
        super("ScanScriptVariablesRequest", [
            { no: 1, name: "names", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ScanScriptVariablesRequest
 */
export const ScanScriptVariablesRequest = new ScanScriptVariablesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScriptReference$Type extends MessageType<ScriptReference> {
    constructor() {
        super("ScriptReference", [
            { no: 1, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ScriptReference
 */
export const ScriptReference = new ScriptReference$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VariableReferences$Type extends MessageType<VariableReferences> {
    constructor() {
        super("VariableReferences", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "scripts", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ScriptReference }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message VariableReferences
 */
export const VariableReferences = new VariableReferences$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScanScriptVariablesResponse$Type extends MessageType<ScanScriptVariablesResponse> {
    constructor() {
        super("ScanScriptVariablesResponse", [
            { no: 1, name: "variables", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => VariableReferences },
            { no: 2, name: "truncated", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ScanScriptVariablesResponse
 */
export const ScanScriptVariablesResponse = new ScanScriptVariablesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Configuration$Type extends MessageType<Configuration> {
    constructor() {
        super("Configuration", [
            { no: 1, name: "path_prefix", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "apps", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ConfigurationApp },
            { no: 6, name: "variables", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Configuration
 */
export const Configuration = new Configuration$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ConfigurationApp$Type extends MessageType<ConfigurationApp> {
    constructor() {
        super("ConfigurationApp", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "grpc", kind: "message", oneof: "app", T: () => GrpcApp },
            { no: 3, name: "twirp", kind: "message", oneof: "app", T: () => TwirpApp },
            { no: 4, name: "openapi", kind: "message", oneof: "app", T: () => OpenApiApp },
            { no: 5, name: "openai", kind: "message", oneof: "app", T: () => OpenAiApp },
            { no: 7, name: "folder", kind: "message", oneof: "app", T: () => FolderApp },
            { no: 8, name: "mcp", kind: "message", oneof: "app", T: () => McpApp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ConfigurationApp
 */
export const ConfigurationApp = new ConfigurationApp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GrpcApp$Type extends MessageType<GrpcApp> {
    constructor() {
        super("GrpcApp", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "proto_dir", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "reflection", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "headers", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 5, name: "tls", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "insecure_skip_verify", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "ca_file", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "client_cert_file", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "client_key_file", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "auth", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "api_key_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message GrpcApp
 */
export const GrpcApp = new GrpcApp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TwirpApp$Type extends MessageType<TwirpApp> {
    constructor() {
        super("TwirpApp", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "proto_dir", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "headers", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message TwirpApp
 */
export const TwirpApp = new TwirpApp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OpenApiApp$Type extends MessageType<OpenApiApp> {
    constructor() {
        super("OpenApiApp", [
            { no: 1, name: "spec_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "headers", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 6, name: "spec_content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "base_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "security_scheme", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "spec_header_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "spec_header_value", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message OpenApiApp
 */
export const OpenApiApp = new OpenApiApp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OpenAiApp$Type extends MessageType<OpenAiApp> {
    constructor() {
        super("OpenAiApp", [
            { no: 1, name: "endpoint", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "headers", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 4, name: "api", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "auth", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "api_key_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message OpenAiApp
 */
export const OpenAiApp = new OpenAiApp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FolderApp$Type extends MessageType<FolderApp> {
    constructor() {
        super("FolderApp", [
            { no: 1, name: "path", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message FolderApp
 */
export const FolderApp = new FolderApp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class McpApp$Type extends MessageType<McpApp> {
    constructor() {
        super("McpApp", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "headers", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 3, name: "auth", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "api_key_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message McpApp
 */
export const McpApp = new McpApp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateConfigurationRequest$Type extends MessageType<UpdateConfigurationRequest> {
    constructor() {
        super("UpdateConfigurationRequest", [
            { no: 1, name: "configuration", kind: "message", T: () => Configuration }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message UpdateConfigurationRequest
 */
export const UpdateConfigurationRequest = new UpdateConfigurationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateConfigurationResponse$Type extends MessageType<UpdateConfigurationResponse> {
    constructor() {
        super("UpdateConfigurationResponse", [
            { no: 1, name: "configuration", kind: "message", T: () => Configuration },
            { no: 2, name: "variable_status", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => VariableStatus }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message UpdateConfigurationResponse
 */
export const UpdateConfigurationResponse = new UpdateConfigurationResponse$Type();
/**
 * @generated ServiceType for protobuf service Api
 */
export const Api = new ServiceType("Api", [
    { name: "Compile", serverStreaming: true, options: {}, I: CompileRequest, O: CompileResponse },
    { name: "OpenApp", options: {}, I: OpenAppRequest, O: OpenAppResponse },
    { name: "InspectOpenApi", options: {}, I: InspectOpenApiRequest, O: InspectOpenApiResponse },
    { name: "InspectGrpc", options: {}, I: InspectGrpcRequest, O: InspectGrpcResponse },
    { name: "InspectMcp", options: {}, I: InspectMcpRequest, O: InspectMcpResponse },
    { name: "GetConfiguration", options: {}, I: GetConfigurationRequest, O: GetConfigurationResponse },
    { name: "WatchConfiguration", serverStreaming: true, options: {}, I: WatchConfigurationRequest, O: GetConfigurationResponse },
    { name: "UpdateConfiguration", options: {}, I: UpdateConfigurationRequest, O: UpdateConfigurationResponse },
    { name: "SetStoredValue", options: {}, I: SetStoredValueRequest, O: StoredValueResponse },
    { name: "ClearStoredValue", options: {}, I: ClearStoredValueRequest, O: StoredValueResponse },
    { name: "ListScripts", options: {}, I: ListScriptsRequest, O: ListScriptsResponse },
    { name: "ReadScript", options: {}, I: ReadScriptRequest, O: ReadScriptResponse },
    { name: "WriteScript", options: {}, I: WriteScriptRequest, O: WriteScriptResponse },
    { name: "CreateScript", options: {}, I: CreateScriptRequest, O: CreateScriptResponse },
    { name: "RenameScript", options: {}, I: RenameScriptRequest, O: RenameScriptResponse },
    { name: "DeleteScript", options: {}, I: DeleteScriptRequest, O: DeleteScriptResponse },
    { name: "ListScriptFolders", options: {}, I: ListScriptFoldersRequest, O: ListScriptFoldersResponse },
    { name: "CreateScriptFolder", options: {}, I: CreateScriptFolderRequest, O: CreateScriptFolderResponse },
    { name: "RenameScriptFolder", options: {}, I: RenameScriptFolderRequest, O: RenameScriptFolderResponse },
    { name: "DeleteScriptFolder", options: {}, I: DeleteScriptFolderRequest, O: DeleteScriptFolderResponse },
    { name: "ScanScriptVariables", options: {}, I: ScanScriptVariablesRequest, O: ScanScriptVariablesResponse }
]);
