// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "api.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Api } from "./api";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { ReadScriptResponse } from "./api";
import type { ReadScriptRequest } from "./api";
import type { ListScriptsResponse } from "./api";
import type { ListScriptsRequest } from "./api";
import type { StoredValueResponse } from "./api";
import type { ClearStoredValueRequest } from "./api";
import type { SetStoredValueRequest } from "./api";
import type { UpdateConfigurationResponse } from "./api";
import type { UpdateConfigurationRequest } from "./api";
import type { WatchConfigurationRequest } from "./api";
import type { GetConfigurationResponse } from "./api";
import type { GetConfigurationRequest } from "./api";
import type { InspectMcpResponse } from "./api";
import type { InspectMcpRequest } from "./api";
import type { InspectGrpcResponse } from "./api";
import type { InspectGrpcRequest } from "./api";
import type { InspectOpenApiResponse } from "./api";
import type { InspectOpenApiRequest } from "./api";
import type { OpenAppResponse } from "./api";
import type { OpenAppRequest } from "./api";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CompileResponse } from "./api";
import type { CompileRequest } from "./api";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service Api
 */
export interface IApiClient {
    /**
     * Compile streams the compilation of an app's proto surface: each log line as it
     * is written, then one last message carrying the terminal status and, on success,
     * the generated sources and the stub.
     *
     * @generated from protobuf rpc: Compile
     */
    compile(input: CompileRequest, options?: RpcOptions): ServerStreamingCall<CompileRequest, CompileResponse>;
    /**
     * @generated from protobuf rpc: OpenApp
     */
    openApp(input: OpenAppRequest, options?: RpcOptions): UnaryCall<OpenAppRequest, OpenAppResponse>;
    /**
     * @generated from protobuf rpc: InspectOpenApi
     */
    inspectOpenApi(input: InspectOpenApiRequest, options?: RpcOptions): UnaryCall<InspectOpenApiRequest, InspectOpenApiResponse>;
    /**
     * @generated from protobuf rpc: InspectGrpc
     */
    inspectGrpc(input: InspectGrpcRequest, options?: RpcOptions): UnaryCall<InspectGrpcRequest, InspectGrpcResponse>;
    /**
     * @generated from protobuf rpc: InspectMcp
     */
    inspectMcp(input: InspectMcpRequest, options?: RpcOptions): UnaryCall<InspectMcpRequest, InspectMcpResponse>;
    /**
     * @generated from protobuf rpc: GetConfiguration
     */
    getConfiguration(input: GetConfigurationRequest, options?: RpcOptions): UnaryCall<GetConfigurationRequest, GetConfigurationResponse>;
    /**
     * WatchConfiguration streams the configuration file as it is edited: one message
     * carrying the whole configuration each time the file changes. What changed is
     * never asked for afterwards, because the message is the new configuration.
     *
     * @generated from protobuf rpc: WatchConfiguration
     */
    watchConfiguration(input: WatchConfigurationRequest, options?: RpcOptions): ServerStreamingCall<WatchConfigurationRequest, GetConfigurationResponse>;
    /**
     * @generated from protobuf rpc: UpdateConfiguration
     */
    updateConfiguration(input: UpdateConfigurationRequest, options?: RpcOptions): UnaryCall<UpdateConfigurationRequest, UpdateConfigurationResponse>;
    /**
     * @generated from protobuf rpc: SetStoredValue
     */
    setStoredValue(input: SetStoredValueRequest, options?: RpcOptions): UnaryCall<SetStoredValueRequest, StoredValueResponse>;
    /**
     * @generated from protobuf rpc: ClearStoredValue
     */
    clearStoredValue(input: ClearStoredValueRequest, options?: RpcOptions): UnaryCall<ClearStoredValueRequest, StoredValueResponse>;
    /**
     * @generated from protobuf rpc: ListScripts
     */
    listScripts(input: ListScriptsRequest, options?: RpcOptions): UnaryCall<ListScriptsRequest, ListScriptsResponse>;
    /**
     * @generated from protobuf rpc: ReadScript
     */
    readScript(input: ReadScriptRequest, options?: RpcOptions): UnaryCall<ReadScriptRequest, ReadScriptResponse>;
}
/**
 * @generated from protobuf service Api
 */
export class ApiClient implements IApiClient, ServiceInfo {
    typeName = Api.typeName;
    methods = Api.methods;
    options = Api.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Compile streams the compilation of an app's proto surface: each log line as it
     * is written, then one last message carrying the terminal status and, on success,
     * the generated sources and the stub.
     *
     * @generated from protobuf rpc: Compile
     */
    compile(input: CompileRequest, options?: RpcOptions): ServerStreamingCall<CompileRequest, CompileResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CompileRequest, CompileResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: OpenApp
     */
    openApp(input: OpenAppRequest, options?: RpcOptions): UnaryCall<OpenAppRequest, OpenAppResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<OpenAppRequest, OpenAppResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: InspectOpenApi
     */
    inspectOpenApi(input: InspectOpenApiRequest, options?: RpcOptions): UnaryCall<InspectOpenApiRequest, InspectOpenApiResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<InspectOpenApiRequest, InspectOpenApiResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: InspectGrpc
     */
    inspectGrpc(input: InspectGrpcRequest, options?: RpcOptions): UnaryCall<InspectGrpcRequest, InspectGrpcResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<InspectGrpcRequest, InspectGrpcResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: InspectMcp
     */
    inspectMcp(input: InspectMcpRequest, options?: RpcOptions): UnaryCall<InspectMcpRequest, InspectMcpResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<InspectMcpRequest, InspectMcpResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetConfiguration
     */
    getConfiguration(input: GetConfigurationRequest, options?: RpcOptions): UnaryCall<GetConfigurationRequest, GetConfigurationResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetConfigurationRequest, GetConfigurationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * WatchConfiguration streams the configuration file as it is edited: one message
     * carrying the whole configuration each time the file changes. What changed is
     * never asked for afterwards, because the message is the new configuration.
     *
     * @generated from protobuf rpc: WatchConfiguration
     */
    watchConfiguration(input: WatchConfigurationRequest, options?: RpcOptions): ServerStreamingCall<WatchConfigurationRequest, GetConfigurationResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<WatchConfigurationRequest, GetConfigurationResponse>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateConfiguration
     */
    updateConfiguration(input: UpdateConfigurationRequest, options?: RpcOptions): UnaryCall<UpdateConfigurationRequest, UpdateConfigurationResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateConfigurationRequest, UpdateConfigurationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetStoredValue
     */
    setStoredValue(input: SetStoredValueRequest, options?: RpcOptions): UnaryCall<SetStoredValueRequest, StoredValueResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetStoredValueRequest, StoredValueResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ClearStoredValue
     */
    clearStoredValue(input: ClearStoredValueRequest, options?: RpcOptions): UnaryCall<ClearStoredValueRequest, StoredValueResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClearStoredValueRequest, StoredValueResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListScripts
     */
    listScripts(input: ListScriptsRequest, options?: RpcOptions): UnaryCall<ListScriptsRequest, ListScriptsResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListScriptsRequest, ListScriptsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadScript
     */
    readScript(input: ReadScriptRequest, options?: RpcOptions): UnaryCall<ReadScriptRequest, ReadScriptResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadScriptRequest, ReadScriptResponse>("unary", this._transport, method, opt, input);
    }
}
