// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSourceFile(arg1) {
  return window['go']['main']['App']['LoadSourceFile'](arg1);
}

export function LoadStub(arg1) {
  return window['go']['main']['App']['LoadStub'](arg1);
}

export function Twirp(arg1, arg2) {
  return window['go']['main']['App']['Twirp'](arg1, arg2);
}
