// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream(arg1) {
  return window['go']['main']['App']['CancelStream'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function Target(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Target'](arg1, arg2, arg3, arg4, arg5);
}

export function TargetServerStream(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TargetServerStream'](arg1, arg2, arg3, arg4, arg5);
}

export function Twirp(arg1, arg2) {
  return window['go']['main']['App']['Twirp'](arg1, arg2);
}
