// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelStream(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function OpenDirectoryDialog():Promise<string>;

export function Target(arg1:string,arg2:string,arg3:Array<number>,arg4:number,arg5:string):Promise<main.TargetResult>;

export function TargetServerStream(arg1:string,arg2:string,arg3:Array<number>,arg4:string,arg5:string):Promise<void>;

export function Twirp(arg1:string,arg2:Array<number>):Promise<Array<number>>;
