// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function Target(arg1:string,arg2:string,arg3:Array<number>):Promise<Array<number>>;

export function Twirp(arg1:string,arg2:Array<number>):Promise<Array<number>>;
