// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {compiler} from '../models';

export function Compile(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<compiler.Status>;
