// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MCPInfo is reported to the UI so it can show the connection command. Error is set
 * when the server couldn't start (e.g. the fixed port was already in use).
 */
export class MCPInfo {
    "enabled": boolean;
    "url": string;
    "token": string;
    "error": string;

    /**
     * ConfigurationPaths is where each client keeps the file its snippet goes
     * into, keyed by the client the footer shows it under.
     */
    "configurationPaths": { [_ in string]?: string };

    /** Creates a new MCPInfo instance. */
    constructor($$source: Partial<MCPInfo> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("configurationPaths" in $$source)) {
            this["configurationPaths"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MCPInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MCPInfo {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("configurationPaths" in $$parsedSource) {
            $$parsedSource["configurationPaths"] = $$createField4_0($$parsedSource["configurationPaths"]);
        }
        return new MCPInfo($$parsedSource as Partial<MCPInfo>);
    }
}

/**
 * ScriptFile is the on-disk representation of a Kaja script.
 * For ListScripts only Path, Name and Folder are populated; Content is fetched
 * on demand via ReadScriptFile.
 */
export class ScriptFile {
    "path": string;
    "name": string;

    /**
     * Relative to the scripts root, forward-slashed. Empty for a file at the root.
     */
    "folder": string;
    "content": string;

    /** Creates a new ScriptFile instance. */
    constructor($$source: Partial<ScriptFile> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("folder" in $$source)) {
            this["folder"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptFile instance from a string or object.
     */
    static createFrom($$source: any = {}): ScriptFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScriptFile($$parsedSource as Partial<ScriptFile>);
    }
}

/**
 * TargetResult holds the response from a Target call. StatusCode marks a body that
 * is a structured upstream failure rather than the method's response.
 * RequestHeaders/ResponseHeaders are what an in-process app exchanged with its
 * upstream, surfaced in the Headers view. DurationMs is the upstream exchange as this
 * process measured it — the call without the webview round trip — which the UI shows
 * in place of its own timing.
 */
export class TargetResult {
    "body": string;
    "statusCode": number;
    "status": string;
    "requestHeaders"?: { [_ in string]?: string };
    "responseHeaders"?: { [_ in string]?: string };

    /**
     * What a gRPC server answered with. That lane is a bridge rather than a hop —
     * the same call is forwarded — so the metadata is the response's own, the way
     * the web proxy hands it back as gRPC-Web trailers.
     */
    "trailers"?: { [_ in string]?: string };
    "durationMs": number;

    /** Creates a new TargetResult instance. */
    constructor($$source: Partial<TargetResult> = {}) {
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("statusCode" in $$source)) {
            this["statusCode"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TargetResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TargetResult {
        const $$createField0_0 = $Create.ByteSlice;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("body" in $$parsedSource) {
            $$parsedSource["body"] = $$createField0_0($$parsedSource["body"]);
        }
        if ("requestHeaders" in $$parsedSource) {
            $$parsedSource["requestHeaders"] = $$createField3_0($$parsedSource["requestHeaders"]);
        }
        if ("responseHeaders" in $$parsedSource) {
            $$parsedSource["responseHeaders"] = $$createField4_0($$parsedSource["responseHeaders"]);
        }
        if ("trailers" in $$parsedSource) {
            $$parsedSource["trailers"] = $$createField5_0($$parsedSource["trailers"]);
        }
        return new TargetResult($$parsedSource as Partial<TargetResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
