#!/bin/sh
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
NC='\033[0m' # No Color

# Kill background demo-app when the script exits
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

cd "$(dirname "$0")/.."

# Load environment variables from .env file if present
if [ -f .env ]; then
    echo "Loading environment variables from .env file..."
    set -a
    source .env
    set +a
fi

cd ./demo

if [ "$RPC_PROTOCOL" = "grpc" ]; then
    echo "Building gRPC demo app"
    go build -o /tmp/demo-app ./cmd/grpc-server
else
    echo "Building Twirp demo app"
    go build -o /tmp/demo-app ./cmd/twirp-server
fi

/tmp/demo-app &

# Stop and remove the container if it already exists
docker rm -f kaja-dev &> /dev/null || true

cd ".."

docker build . -t kaja-dev:latest

rm pipe &> /dev/null || true
mkfifo pipe

docker run --name kaja-dev -a STDOUT -p 41520:41520 \
    -v $PWD/demo:/workspace \
    -e BASE_URL="http://host.docker.internal:41521" RPC_PROTOCOL=$RPC_PROTOCOL --add-host=host.docker.internal:host-gateway kaja-dev:latest > pipe &

while IFS= read -r line
do
  echo "$line"
  if [[ "$line" == *"Server started"* ]]; then
    break
  fi
done < pipe

rm pipe

# Open kaja in a default web browser
echo -e "${GREEN}Opening kaja URL http://localhost:41520/ in your default web browser${NC}"
python3 -m webbrowser http://localhost:41520/

cat