#!/bin/sh
set -e

source "$(dirname "$0")/common"

setup_trap

cd "$(dirname "$0")/.."

export GOBIN=$PWD/server/build
export PATH=$GOBIN:$PATH

build_demo_apps
start_demo_apps

# Stop and remove the container if it already exists
docker rm -f kaja-dev &> /dev/null || true

docker build . -t kaja-dev:latest --build-arg RUN_TESTS=true

rm pipe &> /dev/null || true
mkfifo pipe

# localhost in kaja.json needs to be replaced with host.docker.internal when running in Docker
# Use a temporary file and make the replacement there
sed 's/localhost/host.docker.internal/g' ./workspace/kaja.json > /tmp/kaja.json

docker run --name kaja-dev -a STDOUT -p 41520:41520 \
    -v $PWD/workspace:/workspace \
    -v /tmp/kaja.json:/workspace/kaja.json \
    --add-host=host.docker.internal:host-gateway kaja-dev:latest > pipe &

while IFS= read -r line
do
  echo "$line"
  if [[ "$line" == *"Server started"* ]]; then
    break
  fi
done < pipe

rm pipe

# Open kaja in a default web browser
echo "Opening kaja URL http://localhost:41520/ in your default web browser"
python3 -m webbrowser http://localhost:41520/

cat