#!/bin/sh
set -e

cd "$(dirname "$0")/.."

# Stop and remove the container if it already exists
docker rm -f kaja-dev &> /dev/null || true

GIT_REF=$(git rev-parse HEAD 2>/dev/null || echo "")
docker build . -t kaja-dev:latest --build-arg RUN_TESTS=true --build-arg GIT_REF=$GIT_REF

rm pipe &> /dev/null || true
mkfifo pipe

docker run --name kaja-dev -a STDOUT -p 41520:41520 \
    -v $PWD/workspace:/workspace \
    kaja-dev:latest > pipe &

while IFS= read -r line
do
  echo "$line"
  if [[ "$line" == *"Server started"* ]]; then
    break
  fi
done < pipe

rm pipe

# Open kaja in a default web browser
echo "Opening kaja URL http://localhost:41520/ in your default web browser"
python3 -m webbrowser http://localhost:41520/

cat