// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/search-service.proto

package demo_app

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage int32                  `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_search_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *SearchRequest) GetResultPerPage() int32 {
	if x != nil {
		return x.ResultPerPage
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Result              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_search_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets      []string               `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`
	IsAd          bool                   `protobuf:"varint,4,opt,name=is_ad,json=isAd,proto3" json:"is_ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_search_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Result) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Result) GetSnippets() []string {
	if x != nil {
		return x.Snippets
	}
	return nil
}

func (x *Result) GetIsAd() bool {
	if x != nil {
		return x.IsAd
	}
	return false
}

type IndexRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Result           *Result                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Position         Position               `protobuf:"varint,2,opt,name=position,proto3,enum=lib.Position" json:"position,omitempty"`
	AdditionalCopies uint64                 `protobuf:"varint,3,opt,name=additional_copies,json=additionalCopies,proto3" json:"additional_copies,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_proto_search_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{3}
}

func (x *IndexRequest) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *IndexRequest) GetPosition() Position {
	if x != nil {
		return x.Position
	}
	return Position_TOP
}

func (x *IndexRequest) GetAdditionalCopies() uint64 {
	if x != nil {
		return x.AdditionalCopies
	}
	return 0
}

type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Result                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_proto_search_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_service_proto_rawDescGZIP(), []int{4}
}

func (x *IndexResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_search_service_proto protoreflect.FileDescriptor

const file_proto_search_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/search-service.proto\x1a\x14proto/lib/enum.proto\"n\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12&\n" +
	"\x0fresult_per_page\x18\x03 \x01(\x05R\rresultPerPage\"3\n" +
	"\x0eSearchResponse\x12!\n" +
	"\aresults\x18\x01 \x03(\v2\a.ResultR\aresults\"a\n" +
	"\x06Result\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bsnippets\x18\x03 \x03(\tR\bsnippets\x12\x13\n" +
	"\x05is_ad\x18\x04 \x01(\bR\x04isAd\"\x87\x01\n" +
	"\fIndexRequest\x12\x1f\n" +
	"\x06result\x18\x01 \x01(\v2\a.ResultR\x06result\x12)\n" +
	"\bposition\x18\x02 \x01(\x0e2\r.lib.PositionR\bposition\x12+\n" +
	"\x11additional_copies\x18\x03 \x01(\x04R\x10additionalCopies\"0\n" +
	"\rIndexResponse\x12\x1f\n" +
	"\x06result\x18\x01 \x01(\v2\a.ResultR\x06result2b\n" +
	"\rSearchService\x12)\n" +
	"\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\x12&\n" +
	"\x05Index\x12\r.IndexRequest\x1a\x0e.IndexResponseB\x13Z\x11internal/demo-appb\x06proto3"

var (
	file_proto_search_service_proto_rawDescOnce sync.Once
	file_proto_search_service_proto_rawDescData []byte
)

func file_proto_search_service_proto_rawDescGZIP() []byte {
	file_proto_search_service_proto_rawDescOnce.Do(func() {
		file_proto_search_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_service_proto_rawDesc), len(file_proto_search_service_proto_rawDesc)))
	})
	return file_proto_search_service_proto_rawDescData
}

var file_proto_search_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_search_service_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: SearchRequest
	(*SearchResponse)(nil), // 1: SearchResponse
	(*Result)(nil),         // 2: Result
	(*IndexRequest)(nil),   // 3: IndexRequest
	(*IndexResponse)(nil),  // 4: IndexResponse
	(Position)(0),          // 5: lib.Position
}
var file_proto_search_service_proto_depIdxs = []int32{
	2, // 0: SearchResponse.results:type_name -> Result
	2, // 1: IndexRequest.result:type_name -> Result
	5, // 2: IndexRequest.position:type_name -> lib.Position
	2, // 3: IndexResponse.result:type_name -> Result
	0, // 4: SearchService.Search:input_type -> SearchRequest
	3, // 5: SearchService.Index:input_type -> IndexRequest
	1, // 6: SearchService.Search:output_type -> SearchResponse
	4, // 7: SearchService.Index:output_type -> IndexResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_search_service_proto_init() }
func file_proto_search_service_proto_init() {
	if File_proto_search_service_proto != nil {
		return
	}
	file_proto_lib_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_service_proto_rawDesc), len(file_proto_search_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_service_proto_goTypes,
		DependencyIndexes: file_proto_search_service_proto_depIdxs,
		MessageInfos:      file_proto_search_service_proto_msgTypes,
	}.Build()
	File_proto_search_service_proto = out.File
	file_proto_search_service_proto_goTypes = nil
	file_proto_search_service_proto_depIdxs = nil
}
