#!/bin/bash
set -e

cd "$(dirname "$0")/.."

rm -rf desktop/frontend/dist
mkdir desktop/frontend/dist
cp server/build/main.css desktop/frontend/dist/main.css
cp server/build/main.js desktop/frontend/dist/main.js
cp server/templates/index.html desktop/frontend/dist/index.html

# Replace {{.PathPrefix}} with empty string in index.html
sed -i '' 's/{{\.PathPrefix}}//' desktop/frontend/dist/index.html

